letsgetit-hanwha-be15/be15-2nd-letsgetit-newbit

.gitignore, src/main/java/com/newbit/coffeeletter/controller/ChatController.java, src/main/java/com/newbit/coffeeletter/repository/ChatMessageRepository.java, src/main/java/com/newbit/coffeeletter/repository/CoffeeLetterRoomRepository.java, src/main/java/com/newbit/coffeeletter/scheduler/ChatRoomScheduler.java, src/main/java/com/newbit/coffeeletter/service/ChatService.java, src/main/java/com/newbit/coffeeletter/service/ChatServiceImpl.java, src/test/java/com/newbit/coffeeletter/repository/MongoDBConnectionTest.java, src/test/java/com/newbit/coffeeletter/service/ChatServiceTest.java
=> Nbt 125 be 커피레터 채팅방 비활성화 기능

.gitignore, src/main/java/com/newbit/coffeeletter/controller/ChatController.java, src/main/java/com/newbit/coffeeletter/repository/ChatMessageRepository.java, src/main/java/com/newbit/coffeeletter/repository/CoffeeLetterRoomRepository.java, src/main/java/com/newbit/coffeeletter/scheduler/ChatRoomScheduler.java, src/main/java/com/newbit/coffeeletter/service/ChatService.java, src/main/java/com/newbit/coffeeletter/service/ChatServiceImpl.java, src/test/java/com/newbit/coffeeletter/repository/MongoDBConnectionTest.java, src/test/java/com/newbit/coffeeletter/service/ChatServiceTest.java
=> Nbt 127 be 커피레터 채팅방 취소 기능

.gitignore, src/main/java/com/newbit/coffeeletter/controller/ChatController.java, src/main/java/com/newbit/coffeeletter/repository/ChatMessageRepository.java, src/main/java/com/newbit/coffeeletter/repository/CoffeeLetterRoomRepository.java, src/main/java/com/newbit/coffeeletter/scheduler/ChatRoomScheduler.java, src/main/java/com/newbit/coffeeletter/service/ChatService.java, src/main/java/com/newbit/coffeeletter/service/ChatServiceImpl.java, src/test/java/com/newbit/coffeeletter/repository/MongoDBConnectionTest.java, src/test/java/com/newbit/coffeeletter/service/ChatServiceTest.java
=> Nbt 122 be 커피레터 채팅방 조회 기능

.gitignore, src/main/java/com/newbit/coffeeletter/controller/ChatController.java, src/main/java/com/newbit/coffeeletter/repository/ChatMessageRepository.java, src/main/java/com/newbit/coffeeletter/repository/CoffeeLetterRoomRepository.java, src/main/java/com/newbit/coffeeletter/scheduler/ChatRoomScheduler.java, src/main/java/com/newbit/coffeeletter/service/ChatService.java, src/main/java/com/newbit/coffeeletter/service/ChatServiceImpl.java, src/test/java/com/newbit/coffeeletter/repository/MongoDBConnectionTest.java, src/test/java/com/newbit/coffeeletter/service/ChatServiceTest.java
Close #116
웹소켓 핸들러 메세지 송신 저장 기능
=> Nbt 128 be 커피레터 웹소켓 핸들러 메세지 송신 저장 기능

src/main/java/com/newbit/coffeeletter/controller/ChatController.java, src/main/java/com/newbit/coffeeletter/repository/ChatMessageRepository.java
Close #133
PR 누락된 브랜치 스트림 커밋 내용 반영
=> Nbt 134 be pr 누락 코드 124 125 수정 이슈

src/main/java/com/newbit/coffeeletter/controller/ChatController.java, src/main/java/com/newbit/coffeeletter/repository/ChatMessageRepository.java, src/main/java/com/newbit/coffeeletter/service/ChatService.java, src/main/java/com/newbit/coffeeletter/service/ChatServiceImpl.java, src/test/java/com/newbit/coffeeletter/service/ChatServiceTest.java
Close #117 
Close #118 
읽지 않은 체팅 메세지 조회 기능 및 카운트 기능(이슈 통합)
두 가지 기능을 한 번에 명시하는 게 더 효율적이라서 통합함
=> feat:NBT-129 읽지 않은 체팅 메세지 조회 기능 및 카운트 기능(이슈 통합)

src/main/java/com/newbit/coffeeletter/controller/ChatController.java, src/main/java/com/newbit/coffeeletter/repository/ChatMessageRepository.java, src/main/java/com/newbit/coffeeletter/service/ChatService.java, src/main/java/com/newbit/coffeeletter/service/ChatServiceImpl.java, src/test/java/com/newbit/coffeeletter/controller/ChatControllerTest.java, src/test/java/com/newbit/coffeeletter/service/ChatServiceTest.java
Close #119
채팅방 마지막 메세지 조회 기능 구현
=> feat:NBT-131 채팅방 마지막 메세지 조회 기능 구현

build.gradle, src/main/java/com/newbit/coffeeletter/controller/ChatController.java, src/main/java/com/newbit/coffeeletter/dto/ChatMessageDTO.java, src/main/java/com/newbit/coffeeletter/dto/CoffeeLetterRoomDTO.java
Close #136
커피레터 도메인 Swagger 적용
=> docs:NBT-135 커피레터 도메인에 Swagger 적용

src/main/java/com/newbit/post/controller/PostController.java, src/main/java/com/newbit/post/dto/PostDto.java, src/main/java/com/newbit/post/entity/Post.java, src/main/java/com/newbit/post/repository/PostRepository.java, src/main/java/com/newbit/post/service/PostService.java, src/test/java/com/newbit/post/service/PostServiceTest.java
NBT-92 게시글 수정 기능 구현(#80)
게시글 수정 기능 구현
- [O] 단위 테스트 구현완료
=> Nbt 92 be 게시글 수정 기능 구현

src/main/java/com/newbit/coffeeletter/config/WebSocketConfig.java, src/main/java/com/newbit/coffeeletter/controller/WebSocketController.java, src/main/java/com/newbit/coffeeletter/service/ChatServiceImpl.java
없음	
WebSocket Service Bean에 Primary 명시
=> refactor:WebSocket Service Bean에 Primary 명시

src/main/java/com/newbit/purchase/query/controller/ColumnPurchaseHistoryQueryController.java, src/main/java/com/newbit/purchase/query/controller/DiamondHistoryQueryController.java, src/main/java/com/newbit/purchase/query/controller/PointHistoryQueryController.java, src/main/java/com/newbit/purchase/query/repository/AssetHistoryMapper.java, src/main/java/com/newbit/purchase/query/service/DiamondHistoryQueryService.java, src/main/resources/mappers/purchase/AssetHistoryMapper.xml, src/test/java/com/newbit/purchase/query/service/DiamondHistoryQueryServiceTest.java
NBT-67 회원의 다이아 내역 조회 기능 구현 (#55)	
회원 ID로 다이아 내역을 조회하는 기능 구현
쿼리스트링으로 type을 넘겨줘서 획득내역, 소모내역 따로 조회가능
=> feat: NBT-67 회원의 다이아 내역 조회 기능 구현

src/main/java/com/newbit/post/controller/PostController.java, src/main/java/com/newbit/post/dto/response/PostResponse.java, src/main/java/com/newbit/post/entity/Post.java, src/main/java/com/newbit/post/service/PostService.java, src/test/java/com/newbit/post/service/PostServiceTest.java
post 패키지 컴파일 오류 해결했습니다. 
- [O] swagger 구현완료 
- [O] 단위테스트 구현완료
=> fix: comfile-error 수정

src/main/java/com/newbit/post/controller/PostController.java, src/main/java/com/newbit/post/dto/request/PostUpdateRequest.java, src/main/java/com/newbit/post/service/PostService.java, src/test/java/com/newbit/post/service/PostServiceTest.java
=> feat: NBT-93 게시글 삭제 기능 구현

build.gradle, src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/java/com/newbit/user/controller/UserController.java, src/main/java/com/newbit/user/dto/request/FindPasswordDTO.java, src/main/java/com/newbit/user/entity/User.java, src/main/java/com/newbit/user/repository/UserRepository.java, src/main/java/com/newbit/user/service/UserService.java, src/main/java/com/newbit/user/support/MailServiceSupport.java, src/test/java/com/newbit/user/service/FindEmailByNameAndPhoneTest.java, src/test/java/com/newbit/user/service/FindpasswordByEmailTest.java
[NBT-118] [BE] 회원 비밀번호 찾기 기능 구현  close#106
회원 비밀번호 찾기 기능 구현 
파일 병합 커밋은 안 보셔도 됩니다.
[NBT-118]: https://kimjy3520.atlassian.net/browse/NBT-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 118 be 회원 비밀번호 찾기 기능 구현

src/main/java/com/newbit/coffeechat/query/CoffeechatQueryController.java, src/main/java/com/newbit/coffeechat/query/dto/response/RequestTimeDto.java, src/main/java/com/newbit/coffeechat/query/dto/response/RequestTimeListResponse.java, src/main/java/com/newbit/coffeechat/query/mapper/CoffeechatMapper.java, src/main/java/com/newbit/coffeechat/query/service/CoffeechatQueryService.java, src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/resources/mappers/coffeechat/CoffeechatMapper.xml, src/test/java/com/newbit/coffeechat/query/service/CoffeechatQueryServiceTest.java
Nbt 126 be 커피챗 신청 시간 조회 기능 구현 ( jira랑 github랑 오류나서 커피레터 위에 제꺼 이슈가 덧씌워져서 따로 완료할 이슈가 없어 그대로 두겠습니다.)
=> Nbt 126 be 커피챗 신청 시간 조회 기능 구현

src/main/java/com/newbit/post/controller/PostController.java, src/main/java/com/newbit/post/repository/PostRepository.java, src/main/java/com/newbit/post/service/PostService.java
close #86 
PostService에 검색 메서드 (searchPosts) 추가
PostController에 검색 API 엔드포인트 추가 및 Swagger 문서화 적용
=> feat: NBT-98 게시글 검색 기능 구현

src/main/java/com/newbit/auth/controller/AuthController.java, src/main/java/com/newbit/auth/dto/request/LoginRequestDTO.java, src/main/java/com/newbit/auth/dto/request/RefreshTokenRequestDTO.java, src/main/java/com/newbit/auth/dto/response/TokenResponseDTO.java, src/main/java/com/newbit/auth/entity/RefreshToken.java, src/main/java/com/newbit/auth/jwt/JwtAuthenticationFilter.java, src/main/java/com/newbit/auth/jwt/JwtTokenProvider.java, src/main/java/com/newbit/auth/jwt/RestAccessDeniedHandler.java, src/main/java/com/newbit/auth/jwt/RestAuthenticationEntryPoint.java, src/main/java/com/newbit/auth/model/CustomUser.java, src/main/java/com/newbit/auth/repository/RefreshTokenRepository.java, src/main/java/com/newbit/auth/service/AuthService.java, src/main/java/com/newbit/auth/service/CustomUserDetailsService.java, src/main/java/com/newbit/auth/utils/HMACKeyGenerator.java, src/main/java/com/newbit/common/config/SecurityConfig.java, src/main/java/com/newbit/user/entity/User.java, src/test/java/com/newbit/auth/service/AuthServiceTest.java, src/test/java/com/newbit/auth/service/CustomUserDetailsServiceTest.java
[NBT-114] [BE] 로그인 기능 구현 close#102
로그인 기능 구현
- [x ]  단위 테스트
- [x ]  포스트맨 
[NBT-114]: https://kimjy3520.atlassian.net/browse/NBT-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 114 be 로그인 기능 구현

src/main/java/com/newbit/post/controller/PostController.java, src/main/java/com/newbit/post/dto/response/PostListResponse.java, src/main/java/com/newbit/post/service/PostService.java, src/test/java/com/newbit/post/service/PostServiceTest.java
🛰️ Issue
close #87 
🪐 작업 내용
게시글 목록 조회 기능 구현
📚 논의하고싶은 내용 (선택)
✅ Check List (선택)
[x] SWAGGER
[x] 단위테스트
=> Nbt 99 be 게시글 목록 조회 기능 구현

src/main/java/com/newbit/post/service/PostService.java
=> fix: postservice-error 수정

src/main/java/com/newbit/post/controller/CommentController.java, src/test/java/com/newbit/post/service/PostServiceTest.java
=> fix: postservicetest-error 수정

src/main/java/com/newbit/post/controller/CommentController.java, src/main/java/com/newbit/post/service/CommentService.java, src/test/java/com/newbit/post/service/CommentServiceTest.java, src/test/java/com/newbit/post/service/PostServiceTest.java
close #92 
게시글 ID로 조회 후 soft delete 방식 적용
=> Nbt 104 be 댓글 삭제 기능 구현

src/main/java/com/newbit/auth/controller/AuthController.java, src/main/java/com/newbit/auth/service/AuthService.java, src/test/java/com/newbit/auth/service/AuthLogOutServiceTest.java
[NBT-115] [BE] 로그아웃 기능 구현 close#103
로그아웃 기능 구현
- [ x] 포스트맨
- [ x] 단위 테스트
[NBT-115]: https://kimjy3520.atlassian.net/browse/NBT-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 115 be 로그아웃 기능 구현

.github/workflows/pr-review-notify.yml
=> feat:add-discord-review-alert

.github/workflows/pr-review-notify.yml
=> feat:add-discord-review-alert revised

src/main/java/com/newbit/column/service/ColumnRequestService.java, src/main/java/com/newbit/user/service/MentorService.java, src/test/java/com/newbit/column/service/ColumnRequestServiceTest.java, src/test/java/com/newbit/column/service/ColumnServiceTest.java
Nbt 78 be 멘토 칼럼 등록 요청 기능 구현	
ColumnServiceTest 수정 완료
=> fix : Nbt 78 be 멘토 칼럼 등록 요청 기능 구현

src/main/java/com/newbit/coffeechat/command/application/controller/CoffeechatCommandController.java, src/main/java/com/newbit/coffeechat/command/application/dto/request/CoffeechatCreateRequest.java, src/main/java/com/newbit/coffeechat/command/application/dto/request/RequestTimeDto.java, src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java, src/main/java/com/newbit/coffeechat/command/domain/aggregate/RequestTime.java, src/main/java/com/newbit/coffeechat/command/domain/repository/RequestTimeRepository.java, src/main/java/com/newbit/coffeechat/command/infrastructure/repository/JpaRequestTimeRepository.java, src/main/java/com/newbit/common/exception/ErrorCode.java, src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
close #60 
커피챗 신청시간을 같이 등록할 수 있도록 서비스 추가 구현 후, controller reqeust 객체 수정했습니다.
(컨트롤러가 아닌 서비스 구현이어서 swagger는 따로 없습니다.)
=> Nbt 72 be 커피챗 신청시간 등록 기능 구현

src/main/java/com/newbit/auth/service/AuthService.java, src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/java/com/newbit/purchase/command/application/service/PointRewardCommandService.java, src/main/java/com/newbit/purchase/command/application/service/PointTransactionCommandService.java, src/test/java/com/newbit/purchase/command/application/service/PointTransactionCommandServiceTest.java
NBT-75 팁 제공 기능 구현(close #63)
- 팁 제공 기능 메서드 구현
- 주는 user, 받는 user의 보유 point값 변경
- point 내역 생성
=> feat: NBT-75 팁 제공 기능 구현

src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/java/com/newbit/purchase/command/application/controller/PurchaseCommandController.java, src/main/java/com/newbit/purchase/command/application/service/PurchaseCommandService.java, src/main/java/com/newbit/purchase/query/controller/ColumnPurchaseHistoryQueryController.java, src/main/java/com/newbit/purchase/query/controller/DiamondHistoryQueryController.java, src/main/java/com/newbit/purchase/query/controller/PointHistoryQueryController.java, src/main/java/com/newbit/purchase/query/controller/SaleHistoryQueryController.java, src/test/java/com/newbit/purchase/command/application/service/PurchaseCommandServiceTest.java
NBT-178 구매 도메인 user id custom user에서 받아오는 방식으로 수정 (close #244)
구매 도메인의 Controller에서 userId를 기존 @PathVariable로 받아오는 방식에서 CustomUser.getUserId()로 받아오는 방식으로 수정
=> feat: NBT-178 구매 도메인 user id custom user에서 받아오는 방식으로 수정

src/main/java/com/newbit/common/config/SwaggerConfig.java
=> fix: SwaggerConfig class 리팩토링

src/main/java/com/newbit/post/controller/PostController.java, src/main/java/com/newbit/post/service/PostService.java, src/test/java/com/newbit/post/service/PostServiceNoticeTest.java
close #95 
공지사항 수정 기능 추가
PostService에 updateNotice() 메서드 구현
로그인한 사용자의 권한이 ROLE_ADMIN일 경우에만 수정 가능
=> Nbt 107 be 공지사항 수정 기능 구현

src/main/java/com/newbit/column/controller/ColumnController.java, src/main/java/com/newbit/column/dto/response/GetMyColumnListResponseDto.java, src/main/java/com/newbit/column/mapper/ColumnMapper.java, src/main/java/com/newbit/column/repository/ColumnRepository.java, src/main/java/com/newbit/column/service/ColumnRequestService.java, src/main/java/com/newbit/column/service/ColumnService.java, src/test/java/com/newbit/column/service/ColumnServiceTest.java
Nbt 159 be 본인 칼럼 조회	
- 멘토가 본인이 작성한 승인된 칼럼들을 조회할 수 있다.
=> Nbt 159 be 본인 칼럼 조회

src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/java/com/newbit/user/controller/UserInfoController.java, src/main/java/com/newbit/user/dto/request/ChangePasswordRequestDTO.java, src/main/java/com/newbit/user/service/UserInfoService.java, src/main/java/com/newbit/user/service/UserService.java, src/main/java/com/newbit/user/support/PasswordValidator.java, src/test/java/com/newbit/user/service/ChangePassswordTest.java
[NBT-181] [BE] 회원 비밀번호 변경 기능 구현 #253
회원 비밀번호 변경 기능 구현
- [ x] 포스트맨
- [ x] 단위 테스트
[NBT-181]: https://kimjy3520.atlassian.net/browse/NBT-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 181 be 회원 비밀번호 변경 기능 구현

src/main/java/com/newbit/coffeechat/command/application/controller/CoffeechatCommandController.java, src/main/java/com/newbit/coffeechat/command/application/dto/request/CoffeechatCreateRequest.java, src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java, src/main/java/com/newbit/coffeechat/command/domain/aggregate/Coffeechat.java, src/main/resources/mappers/coffeechat/CoffeechatMapper.xml, src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
close #250 
멘토 일정 거절 기능 구현
커피챗 등록 시, 시간정보 받는 부분 변경
=> Nbt 180 be 멘토 일정 거절 기능 구현

src/main/java/com/newbit/user/controller/UserInfoController.java, src/main/java/com/newbit/user/dto/request/DeleteUserRequestDTO.java, src/main/java/com/newbit/user/repository/UserRepository.java, src/main/java/com/newbit/user/service/UserInfoService.java, src/test/java/com/newbit/user/service/UnsubscribeServiceTest.java
[NBT-121] [BE] 회원 탈퇴 기능 구현 #109
회원 탈퇴 기능 구현
- [x ] 단위 테스트 
- [x ] 포스트맨
[NBT-121]: https://kimjy3520.atlassian.net/browse/NBT-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 121 be 회원 탈퇴 기능 구현

src/main/java/com/newbit/coffeechat/command/application/controller/CoffeechatCommandController.java, src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java, src/main/java/com/newbit/coffeechat/command/domain/aggregate/Coffeechat.java, src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
close #77 
Nbt 89 be 멘토의 커피챗 종료 기능 구현
=> Nbt 89 be 멘토의 커피챗 종료 기능 구현

src/main/java/com/newbit/purchase/command/application/service/PurchaseCommandService.java, src/main/java/com/newbit/purchase/command/application/service/SaleCommandService.java
NBT-191 구매 도메인 service 계층 refactoring (close #275)
구매 도메인의 Service 계층에서 PurchaseCommandService 가 너무 많은 작업을 담당하고있어 분리
SaleCommadService에 addSaleHistory 메서드 분리
=> refactor: NBT-191 구매 도메인 service 계층 refactoring

src/test/java/com/newbit/purchase/command/application/service/PurchaseCommandServiceTest.java
NBT-193 구매 도메인 테스트 코드 수정(#279)
- 단위 테스트 코드 수정
=> fix: NBT-193 구매 도메인 테스트 코드 수정

src/main/java/com/newbit/column/controller/SeriesController.java, src/main/java/com/newbit/column/dto/response/GetSeriesDetailResponseDto.java, src/main/java/com/newbit/column/mapper/SeriesMapper.java, src/main/java/com/newbit/column/service/SeriesService.java, src/test/java/com/newbit/column/service/SeriesServiceTest.java
Nbt 190 시리즈 상세 조회 기능 구현	
1. 시리즈 ID를 기반으로 상세 정보 조회
2. 존재하지 않는 시리즈일 경우 SERIES_NOT_FOUND 예외 발생
=> Nbt 190 시리즈 상세 조회 기능 구현

src/main/java/com/newbit/user/controller/UserInfoController.java, src/main/java/com/newbit/user/dto/response/OhterUserProfileDTO.java, src/main/java/com/newbit/user/mapper/UserMapper.java, src/main/java/com/newbit/user/service/UserQueryService.java, src/main/resources/mappers/user/OhterUserProfile.xml, src/test/java/com/newbit/user/service/ProfileServiceTest.java
[NBT-157] [BE] 회원 프로필 조회 기능 #201
회원 프로필 조회 기능 구현
- [x ] 단위 테스트
- [x ] 포스트맨
[NBT-157]: https://kimjy3520.atlassian.net/browse/NBT-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 157 be 회원 프로필 조회 기능

src/main/java/com/newbit/column/controller/SeriesController.java, src/main/java/com/newbit/column/dto/response/GetMySeriesListResponseDto.java, src/main/java/com/newbit/column/mapper/SeriesMapper.java, src/main/java/com/newbit/column/repository/SeriesRepository.java, src/main/java/com/newbit/column/service/SeriesService.java, src/test/java/com/newbit/column/service/SeriesServiceTest.java
Nbt 189 멘토가 생성한 시리즈 목록 조회 본인 전용 기능 구현	
1. 멘토 본인 검증, 시리즈 조회, DTO 매핑 로직 테스트
=> Nbt 189 멘토가 생성한 시리즈 목록 조회 본인 전용 기능 구현

src/main/java/com/newbit/column/controller/SeriesController.java, src/main/java/com/newbit/column/domain/Series.java, src/main/java/com/newbit/column/dto/response/GetMySeriesListResponseDto.java, src/main/java/com/newbit/column/dto/response/GetSeriesColumnsResponseDto.java, src/main/java/com/newbit/column/dto/response/GetSeriesDetailResponseDto.java, src/main/java/com/newbit/column/dto/response/UpdateSeriesResponseDto.java, src/main/java/com/newbit/column/mapper/SeriesMapper.java, src/main/java/com/newbit/column/service/SeriesService.java, src/test/java/com/newbit/column/service/SeriesServiceTest.java
Nbt 188 시리즈에 포함된 칼럼 목록 조회 기능 구현	
특정 시리즈에 포함된 칼럼 목록을 조회하는 API를 구현
페이징 추후 적용
=> Nbt 188 시리즈에 포함된 칼럼 목록 조회 기능 구현

src/main/java/com/newbit/notification/command/application/dto/request/NotificationSendRequest.java, src/main/java/com/newbit/notification/command/application/dto/response/NotificationSendResponse.java, src/main/java/com/newbit/notification/command/application/service/NotificationCommandService.java, src/main/java/com/newbit/notification/command/domain/aggregate/Notification.java, src/main/java/com/newbit/notification/query/dto/NotificationResponse.java, src/main/resources/mappers/notification/NotificationMapper.xml, src/test/java/com/newbit/notification/command/application/service/NotificationCommandServiceTest.java
NBT-204 알림 테이블 수정에 따른 반영(#300)
- 알림테이블에 serviceId 필드가 추가되면서 수정사항 반영
- NotificationSendRequest DTO 수정
- NotificationSendResponse DTO 수정
- NotificationResponseDTO 수정
- NotificationMapper.xml 수정
- sendNotification 메서드에서 serviceId도 같이 전송하도록 수
=> [BE] NBT-204 알림 테이블 수정에 따른 반영

src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/java/com/newbit/like/controller/PostLikeController.java, src/main/java/com/newbit/like/dto/request/PostLikeRequest.java, src/main/java/com/newbit/like/dto/response/PostLikeResponse.java, src/main/java/com/newbit/like/entity/Like.java, src/main/java/com/newbit/like/repository/LikeRepository.java, src/main/java/com/newbit/like/service/LikeCommandService.java, src/main/java/com/newbit/like/service/LikeQueryService.java, src/main/java/com/newbit/like/service/PointRewardService.java, src/main/java/com/newbit/like/service/PostLikeService.java, src/test/java/com/newbit/like/service/LikeCommandServiceTest.java, src/test/java/com/newbit/like/service/LikeQueryServiceTest.java, src/test/java/com/newbit/like/service/PostLikeServiceTest.java
Close #83
- 게시글 좋아요 기능
- 게시글 좋아요 시 작성자에게 포인트 지급
- 게시글 좋아요 취소 기능
=> feat:NBT-145-be-신고-50-회-누적-댓글-자동-soft-delete-기능-시스템'

src/main/java/com/newbit/user/controller/UserInfoController.java, src/main/java/com/newbit/user/dto/response/ColumnDTO.java, src/main/java/com/newbit/user/dto/response/MentorProfileDTO.java, src/main/java/com/newbit/user/dto/response/OhterUserProfileDTO.java, src/main/java/com/newbit/user/dto/response/PostDTO.java, src/main/java/com/newbit/user/dto/response/SeriesDTO.java, src/main/java/com/newbit/user/mapper/UserMapper.java, src/main/java/com/newbit/user/service/UserQueryService.java, src/main/resources/mappers/user/MentorProfile.xml, src/main/resources/mappers/user/OhterUserProfile.xml, src/test/java/com/newbit/user/service/MentorinfoServiceTest.java
[NBT-158] [BE] 멘토 프로필 조회 기능 #202
멘토 프로필 조회 기능 구현
- [x ] 단위 테스트 
- [x ] 포스트맨
[NBT-158]: https://kimjy3520.atlassian.net/browse/NBT-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 158 be 멘토 프로필 조회 기능

src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/java/com/newbit/like/service/LikeCommandService.java, src/main/java/com/newbit/subscription/controller/SubscriptionController.java, src/main/java/com/newbit/subscription/dto/request/SubscriptionRequest.java, src/main/java/com/newbit/subscription/dto/response/SubscriptionResponse.java, src/main/java/com/newbit/subscription/dto/response/SubscriptionStatusResponse.java, src/main/java/com/newbit/subscription/entity/Subscription.java, src/main/java/com/newbit/subscription/entity/SubscriptionId.java, src/main/java/com/newbit/subscription/repository/SubscriptionRepository.java, src/main/java/com/newbit/subscription/service/SubscriptionManager.java, src/main/java/com/newbit/subscription/service/SubscriptionService.java, src/main/java/com/newbit/subscription/util/SubscriptionValidator.java, src/test/java/com/newbit/like/integration/PostLikeServiceIntegrationTest.java, src/test/java/com/newbit/subscription/integration/SubscriptionIntegrationTest.java, src/test/java/com/newbit/subscription/service/SubscriptionServiceTest.java
🎯 *작업 개요*
* 시리즈 구독 기능
🔧 *작업 상세 내용* 
* 시리즈 구독 
* 시리즈 구독 취소
✅ *완료 조건*
* 단위 테스트
* Swagger 적용
=> [NBT-154] [BE] 시리즈 구독 및 취소 기능 구현

src/main/java/com/newbit/like/controller/UserLikesController.java, src/main/java/com/newbit/like/dto/response/LikedColumnListResponse.java, src/main/java/com/newbit/like/dto/response/LikedColumnResponse.java, src/main/java/com/newbit/like/dto/response/LikedPostListResponse.java, src/main/java/com/newbit/like/dto/response/LikedPostResponse.java, src/main/java/com/newbit/like/repository/LikeRepository.java, src/main/java/com/newbit/like/service/ColumnLikeService.java, src/main/java/com/newbit/like/service/LikeQueryService.java, src/main/java/com/newbit/like/service/PostLikeService.java, src/test/java/com/newbit/like/integration/PostLikeServiceIntegrationTest.java, src/test/java/com/newbit/like/service/ColumnLikeServiceTest.java, src/test/java/com/newbit/like/service/LikeQueryServiceTest.java, src/test/java/com/newbit/like/service/PostLikeServiceTest.java
Close #85 
- 좋아요한 게시글 목록 페이지네이션 조회
- 좋아요한 칼럼 목록 페이지네이션 조회
=> feat:NBT-97-be-좋아요한-게시글-목록-조회-기능-구현

src/main/java/com/newbit/like/controller/ColumnLikeController.java, src/main/java/com/newbit/like/controller/PostLikeController.java, src/main/java/com/newbit/like/controller/UserLikesController.java
Close #318
likes 컨트롤러  api 주소에 v1 누락 
-> 수정 요청 반영하여 v1 적용
=> Nbt 208 be 좋아요 api url 주소 변경

src/main/java/com/newbit/auth/service/AuthService.java, src/main/java/com/newbit/post/repository/CommentRepository.java, src/main/java/com/newbit/post/repository/PostRepository.java, src/main/java/com/newbit/user/entity/User.java, src/main/java/com/newbit/user/service/SuspensionService.java, src/test/java/com/newbit/auth/service/AuthLogOutServiceTest.java, src/test/java/com/newbit/user/service/SuspensionLoginServiceTest.java, src/test/java/com/newbit/user/service/SuspensionServiceTest.java
[NBT-142] [BE] 회원 정지 기능 #155
회원 정지 기능 구현
- [x ] 단위 테스트 
- [x ] 포스트맨
[NBT-142]: https://kimjy3520.atlassian.net/browse/NBT-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 142 be 회원 정지 기능

src/main/java/com/newbit/coffeechat/command/application/controller/ReviewCommandController.java, src/main/java/com/newbit/coffeechat/command/application/dto/request/ReviewCreateRequest.java, src/main/java/com/newbit/coffeechat/command/application/dto/response/ReviewCommandResponse.java, src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java, src/main/java/com/newbit/coffeechat/command/application/service/ReviewCommandService.java, src/main/java/com/newbit/coffeechat/command/domain/aggregate/Review.java, src/main/java/com/newbit/coffeechat/command/domain/repository/ReviewRepository.java, src/main/java/com/newbit/coffeechat/command/infrastructure/repository/JpaReviewRepository.java, src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/java/com/newbit/user/service/MentorService.java, src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java, src/test/java/com/newbit/coffeechat/command/application/service/ReviewCommandServiceTest.java
close #62 
리뷰 등록 기능 구현
팁, 내용 선택, 별점 필수
=> Nbt 74 be 리뷰 등록 기능 구현

src/main/java/com/newbit/coffeechat/command/application/controller/ReviewCommandController.java, src/main/java/com/newbit/coffeechat/command/application/service/ReviewCommandService.java, src/main/java/com/newbit/coffeechat/command/domain/aggregate/Review.java, src/main/java/com/newbit/coffeechat/command/domain/repository/ReviewRepository.java, src/main/java/com/newbit/common/exception/ErrorCode.java, src/test/java/com/newbit/coffeechat/command/application/service/ReviewCommandServiceTest.java
=> Nbt 112 be 리뷰 삭제 기능 구현

src/main/java/com/newbit/user/controller/UserInfoController.java, src/main/java/com/newbit/user/dto/request/MentorListRequestDTO.java, src/main/java/com/newbit/user/dto/response/MentorListResponseDTO.java, src/main/java/com/newbit/user/mapper/UserMapper.java, src/main/java/com/newbit/user/service/UserQueryService.java, src/main/resources/mappers/user/MentorList.xml, src/test/java/com/newbit/user/service/MentorListServiceTest.java
[NBT-108] [BE]멘토 목록 조회 기능 구현 #96
멘토 목록 조회 기능 구현
- [x ] 단위 테스트 
- [x ] 포스트맨 
[NBT-108]: https://kimjy3520.atlassian.net/browse/NBT-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 108 be 멘토 목록 조회 기능 구현

src/main/java/com/newbit/NewbitApplication.java, src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatAutoConfirmService.java, src/main/java/com/newbit/coffeechat/query/mapper/CoffeechatMapper.java, src/main/java/com/newbit/common/config/RestTemplateConfig.java, src/main/resources/mappers/coffeechat/CoffeechatMapper.xml, src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatAutoConfirmServiceTest.java
close #99 
자동 구매 확정 기능 구현
공통 파일 수정 (NewbitApplication, common/config)
=> Nbt 111 be 자동구매확정 기능 구현

src/main/java/com/newbit/settlement/controller/MentorSettlementController.java, src/main/java/com/newbit/settlement/dto/response/MentorSettlementListResponseDto.java, src/main/java/com/newbit/settlement/dto/response/MentorSettlementSummaryDto.java, src/main/java/com/newbit/settlement/repository/MonthlySettlementHistoryRepository.java, src/main/java/com/newbit/settlement/service/MentorSettlementService.java, src/test/java/com/newbit/settlement/service/MentorSettlementServiceTest.java
Nbt 183 멘토 정산 내역 목록 조회 기능 구현	
- 정산 데이터 페이징 처리 및 최신순 정렬 적용
=> Nbt 183 멘토 정산 내역 목록 조회 기능 구현

src/main/java/com/newbit/common/config/RestTemplateConfig.java, src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/java/com/newbit/payment/command/application/dto/TossPaymentApiDto.java, src/main/java/com/newbit/payment/command/application/dto/request/PaymentApproveRequest.java, src/main/java/com/newbit/payment/command/application/dto/request/PaymentPrepareRequest.java, src/main/java/com/newbit/payment/command/application/dto/response/PaymentApproveResponse.java, src/main/java/com/newbit/payment/command/application/dto/response/PaymentPrepareResponse.java, src/main/java/com/newbit/payment/command/application/service/PaymentCommandService.java, src/main/java/com/newbit/payment/command/application/service/TossPaymentApiClient.java, src/main/java/com/newbit/payment/command/domain/aggregate/Payment.java, src/main/java/com/newbit/payment/command/domain/aggregate/PaymentMethod.java, src/main/java/com/newbit/payment/command/domain/aggregate/PaymentStatus.java, src/main/java/com/newbit/payment/command/domain/repository/PaymentRepository.java, src/main/java/com/newbit/payment/command/infrastructure/JpaPaymentRepository.java, src/main/java/com/newbit/payment/controller/PaymentController.java, src/test/java/com/newbit/payment/command/application/service/PaymentCommandServiceTest.java, src/test/java/com/newbit/payment/command/application/service/TossPaymentApiClientTest.java
Close #239
- 토스 구매 위젯 URL 생성
- 결제 준비
- 결제 승인
- 결제 ID로 결제 정보 조회
- 주문 ID로 결제 정보 조회
- 결제 성공 콜백
- 결제 실패 콜백
=> "feat:NBT-175 다이아몬드 구매 기능"

src/main/java/com/newbit/payment/command/application/dto/PaymentDto.java, src/main/java/com/newbit/payment/command/application/dto/TossPaymentApiDto.java, src/main/java/com/newbit/payment/command/application/dto/request/PaymentCancelRequest.java, src/main/java/com/newbit/payment/command/application/dto/response/PaymentRefundResponse.java, src/main/java/com/newbit/payment/command/application/service/AbstractPaymentService.java, src/main/java/com/newbit/payment/command/application/service/PaymentCommandService.java, src/main/java/com/newbit/payment/command/application/service/PaymentService.java, src/main/java/com/newbit/payment/command/application/service/RefundCommandService.java, src/main/java/com/newbit/payment/command/application/service/TossPaymentApiClient.java, src/main/java/com/newbit/payment/command/domain/aggregate/Refund.java, src/main/java/com/newbit/payment/command/domain/repository/PaymentRepository.java, src/main/java/com/newbit/payment/command/domain/repository/RefundRepository.java, src/main/java/com/newbit/payment/command/infrastructure/JpaPaymentRepository.java, src/main/java/com/newbit/payment/command/infrastructure/JpaRefundRepository.java, src/main/java/com/newbit/payment/controller/AbstractApiController.java, src/main/java/com/newbit/payment/controller/PaymentController.java, src/main/java/com/newbit/payment/controller/RefundController.java, src/test/java/com/newbit/payment/command/application/service/RefundCommandServiceTest.java, src/test/java/com/newbit/payment/command/application/service/TossPaymentApiClientTest.java, src/test/java/com/newbit/payment/command/application/service/TossPaymentApiLiveTest.java, src/test/resources/schema.sql
=> "feat:NBT-176-be-결제-취소-환불,rebase 커밋"

.github/workflows/pr-review-notify.yml
=> feat:git action flow 수정. reviewer 지정 트리거 중복 발생 방지를 위해 sleep (10sec) 추가

src/test/java/com/newbit/auth/service/AuthServiceTest.java, src/test/java/com/newbit/auth/service/CustomUserDetailsServiceTest.java, src/test/java/com/newbit/user/service/UserServiceTest.java
[NBT-221] [BE] 서비스 로직 수정에 따른 테스트 코드 수정 #353
서비스 로직 변경에 따른 테스트 코드 수정
[NBT-221]: https://kimjy3520.atlassian.net/browse/NBT-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 221 be 서비스 로직 수정에 따른 테스트 코드 수정

src/test/java/com/newbit/post/service/PostServiceTest.java
close #360 
PostCreateRequest DTO에서 userId 필드 제거
Swagger 테스트 시 userId 입력 필요 없이 정상 작동하도록 개선
=> Nbt 229 be post create request dto 수정

src/main/java/com/newbit/common/exception/ErrorCode.java
close #363 
에러 코드 도메인 코드 규칙 적용하여 수정
=> refactor: 에러 코드 도메인 코드 규칙 적용하여 수정

src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java, src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
close #368 
커피챗 취소 시 커피레터 채팅방 삭제 로직 추가, 테스트코드 추가
=> Nbt 233 be 커피챗 취소 시 커피레터 채팅방 삭제

src/main/java/com/newbit/common/exception/ErrorCode.java, src/main/java/com/newbit/report/command/application/controller/ReportAdminController.java, src/main/java/com/newbit/report/command/application/controller/ReportCommandController.java, src/main/java/com/newbit/report/query/controller/ReportQueryController.java, src/test/java/com/newbit/report/command/integration/ReportProcessIntegrationTest.java, src/test/java/com/newbit/report/query/controller/ReportQueryControllerTest.java
Close #373
- Report 도메인 공통 비즈니스 에러 코드 적용,
- 권한 로직 적용
- Swagger 적용
=> refactor:NBT-236-236-be Report 도메인 공통 비즈니스 에러 코드 적용, 권한 로직 적용, Swagger 적용

src/main/java/com/newbit/column/dto/request/CreateColumnRequestDto.java, src/main/java/com/newbit/column/mapper/ColumnMapper.java, src/main/java/com/newbit/column/service/ColumnRequestService.java, src/test/java/com/newbit/column/service/ColumnRequestServiceTest.java
NBT-235 칼럼 등록시 시리즈 id도 같이 등록하는 식으로 수정
- Requset DTO 수정
- ColumnMapper 수정
- 칼럼 등록 요청 로직 수정
- test 코드 수정
=> [BE] NBT-235 칼럼 등록시 시리즈 id도 같이 등록하는 식으로 수정

src/main/java/com/newbit/coffeechat/query/controller/CoffeechatQueryController.java
=> feat: 컨트ë¡ix¬에서 입력값 오류 수정

.github/workflows/pr-review-notify.yml
=> fix:리뷰 2명 이상 지정시 PR 알람 트리거 중복 동작되는 코드 개선

src/main/resources/mappers/coffeechat/CoffeechatMapper.xml
=> fix : mapper.xml ã수정

src/main/java/com/newbit/common/exception/GlobalExceptionHandler.java
=> refactor : 공통 에러 핸들러 주석 해제

src/main/java/com/newbit/auth/jwt/JwtAuthenticationFilter.java
=> fix : ìtime 모듈 초기화 로직 추가

README.md
=> docs:readme 초안 작성

src/main/java/com/newbit/coffeechat/command/application/service/ReviewCommandService.java, src/main/java/com/newbit/like/service/PointRewardService.java, src/main/java/com/newbit/post/service/CommentService.java, src/main/java/com/newbit/post/service/PostService.java, src/main/java/com/newbit/purchase/command/application/service/PointTransactionCommandService.java, src/main/java/com/newbit/purchase/command/application/service/PurchaseCommandService.java, src/main/java/com/newbit/purchase/command/domain/PointTypeConstants.java, src/main/java/com/newbit/user/service/LoginService.java, src/test/java/com/newbit/coffeechat/command/application/service/ReviewCommandServiceTest.java, src/test/java/com/newbit/purchase/command/application/service/PointTransactionCommandServiceTest.java
close #394 
java에서 point type 하드코딩 되어있는 부분 상수 클래스로 교체 완료
=> Nbt 244 java에서 point type 하드코딩 되어있는 부분 상수 클래스로 바꾸기

src/main/java/com/newbit/coffeechat/query/controller/CoffeechatQueryController.java, src/main/java/com/newbit/coffeechat/query/controller/ReviewQueryController.java, src/main/java/com/newbit/user/service/MentorService.java
=> refactor : mentorEntity 대신 mentorId 가져오는 방식으로 수정

src/main/java/com/newbit/purchase/command/application/service/PurchaseCommandService.java, src/main/java/com/newbit/user/service/UserService.java, src/test/java/com/newbit/purchase/command/application/service/PurchaseCommandServiceTest.java
NBT-251 purchase 캡슐화 점검 코드 수정 및 msa 적용 시 수정 필요 목록 작성(close #402)
- PurchaseCommandService 수정
=> [BE] NBT-251 purchase 캡슐화 점검 코드 수정 및 msa 적용 시 수정 필요 목록 작성

src/main/java/com/newbit/user/controller/UserInfoController.java, src/main/java/com/newbit/user/dto/response/OtherUserProfileDTO.java, src/main/java/com/newbit/user/mapper/UserMapper.java, src/main/java/com/newbit/user/service/UserQueryService.java, src/main/resources/mappers/user/OtherUserProfile.xml, src/test/java/com/newbit/user/service/ProfileServiceTest.java
=> fix: NBT-157 오타 수정

src/main/java/com/newbit/column/domain/Column.java, src/main/java/com/newbit/column/domain/Series.java, src/main/java/com/newbit/column/mapper/ColumnMapper.java, src/main/java/com/newbit/column/repository/ColumnRepository.java, src/main/java/com/newbit/column/repository/ColumnRequestRepository.java, src/main/java/com/newbit/column/repository/SeriesRepository.java, src/main/java/com/newbit/column/service/AdminColumnService.java, src/main/java/com/newbit/column/service/ColumnRequestService.java, src/main/java/com/newbit/column/service/ColumnService.java, src/main/java/com/newbit/column/service/SeriesService.java, src/main/java/com/newbit/user/service/MentorService.java, src/test/java/com/newbit/column/service/ColumnRequestServiceTest.java, src/test/java/com/newbit/column/service/ColumnServiceTest.java, src/test/java/com/newbit/column/service/SeriesServiceTest.java
=> fix: Long mentorId로 수정

src/main/java/com/newbit/post/controller/CommentController.java, src/main/java/com/newbit/post/controller/PostController.java, src/main/java/com/newbit/post/entity/Comment.java, src/main/java/com/newbit/post/entity/Post.java, src/main/java/com/newbit/post/repository/PostRepository.java, src/main/java/com/newbit/post/service/CommentService.java, src/main/java/com/newbit/post/service/PostService.java, src/test/java/com/newbit/post/service/CommentServiceTest.java, src/test/java/com/newbit/post/service/PostServiceTest.java
close #409 	
게시글에 대한 좋아요 및 신고 기능을 PostService에 추가
댓글 신고 기능을 CommentService에 구현
각 엔터티(Post, Comment)에 신고/좋아요 수 증가 메서드를 정의
게시글 작성자 ID를 조회하는 기능을 PostService에 추가
관련 기능을 PostController, CommentController에 각각 연결
=> Nbt 255 post 도메인 서비스 구현 요청

src/main/java/com/newbit/column/service/ColumnService.java, src/main/java/com/newbit/column/service/SeriesService.java, src/main/java/com/newbit/like/dto/response/LikedColumnResponse.java, src/main/java/com/newbit/like/dto/response/LikedPostResponse.java, src/main/java/com/newbit/like/entity/Like.java, src/main/java/com/newbit/like/service/LikeCommandService.java, src/main/java/com/newbit/like/service/LikeQueryService.java, src/main/java/com/newbit/like/service/PointRewardService.java, src/main/java/com/newbit/like/service/PostLikeService.java, src/main/java/com/newbit/post/service/PostService.java, src/main/java/com/newbit/subscription/dto/response/SubscriberCountResponse.java, src/main/java/com/newbit/subscription/dto/response/SubscriptionStatusResponse.java, src/main/java/com/newbit/subscription/entity/Subscription.java, src/main/java/com/newbit/subscription/entity/SubscriptionId.java, src/main/java/com/newbit/subscription/service/SubscriptionCommandService.java, src/main/java/com/newbit/subscription/service/SubscriptionService.java, src/test/java/com/newbit/like/service/LikeCommandServiceTest.java, src/test/java/com/newbit/like/service/LikeQueryServiceTest.java, src/test/java/com/newbit/subscription/integration/SubscriptionIntegrationTest.java, src/test/java/com/newbit/subscription/service/SubscriptionServiceTest.java
Close #397
- post service, column service에 기본 단일 값 get 메서드 추가(id, 제목 등)
- like, subscription 도메인 의존성 주입 수정
- like, subscription setter 삭제
- 피보나치 함수 100 이하 값은 직접 확인하도록 수정(O(1) 시간 복잡도) 그 이상은 공식 사용
- 예외 처리 간소화(로그 일부 삭제)
- 테스트 코드 의존성 주입 수정
=> Nbt 246 like 도메인 캡슐화 점검 코드 수정 및 msa 적용 시 수정 필요 목록 작성

src/main/java/com/newbit/settlement/controller/MentorSettlementController.java, src/main/java/com/newbit/settlement/entity/MonthlySettlementHistory.java, src/main/java/com/newbit/settlement/repository/MonthlySettlementHistoryRepository.java, src/main/java/com/newbit/settlement/service/MentorSettlementService.java, src/main/java/com/newbit/user/service/UserQueryService.java, src/main/java/com/newbit/user/support/MailServiceSupport.java, src/test/java/com/newbit/column/service/AdminColumnServiceTest.java, src/test/java/com/newbit/column/service/ColumnServiceTest.java, src/test/java/com/newbit/settlement/service/MentorSettlementServiceTest.java
=> Nbt 257 정산 기능 mentor id로 수정

src/test/java/com/newbit/purchase/command/application/service/PurchaseCommandServiceTest.java
NBT-260 PurchaseComandServiceTest 코드 수정 (#418)
- PurchaseCommandServiceTest 코드 수정
=> [BE] NBT-260 PurchaseComandServiceTest 코드 수정

src/main/java/com/newbit/post/service/ReportCountService.java, src/main/java/com/newbit/user/port/ReportCountPort.java, src/main/java/com/newbit/user/service/SuspensionService.java, src/test/java/com/newbit/user/service/SuspensionLoginServiceTest.java, src/test/java/com/newbit/user/service/SuspensionServiceTest.java
[NBT-258] User 도메인 캡슐화 점검, 코드 수정 및 MSA 적용 시 수정 필요 목록 작성
[NBT-258]: https://kimjy3520.atlassian.net/browse/NBT-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 258 user 도메인 캡슐화 점검 코드 수정 및 msa 적용 시 수정 필요 목록 작성

README.md, src/main/java/com/newbit/post/service/CommentService.java, src/main/java/com/newbit/post/service/PostService.java, src/main/java/com/newbit/report/command/application/controller/ReportAdminController.java, src/main/java/com/newbit/report/command/application/dto/request/ReportCreateRequest.java, src/main/java/com/newbit/report/command/application/dto/request/ReportUpdateRequest.java, src/main/java/com/newbit/report/command/application/service/ReportCommandService.java, src/main/java/com/newbit/report/command/domain/aggregate/Report.java, src/main/java/com/newbit/report/command/domain/repository/ReportRepository.java, src/main/java/com/newbit/report/command/infrastructure/repository/JpaReportRepository.java, src/test/java/com/newbit/report/command/application/service/ReportCommandServiceTest.java, src/test/java/com/newbit/report/command/integration/ReportIntegrationTest.java, src/test/java/com/newbit/report/command/integration/ReportProcessIntegrationTest.java
Close #400	
- 의존성 문제 수정
- 테스트 코드 수정
- post, column 도메인 필요 서비스 메서드 추가
=> refactor:NBT-250 report 도메인 캡슐화 점검 코드 수정

newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatCommandServiceTest.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/ReviewCommandServiceTest.java, newbit-gateway/src/main/resources/bootstrap.yml
=> refactor: 커피챗 도메인 테스트 수정

newbit-gateway/src/main/resources/application.yml
=> refactor: 리팩토링 - yaml

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/query/controller/ReportQueryController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/query/service/ReportQueryService.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/like/integration/ColumnLikeServiceIntegrationTest.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/report/query/controller/ReportQueryControllerTest.java
- report api 미작동 문제 수정
- reportquery bean 등록 문제 수정
=> fix: report 도메인 Bean 에러 수정

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/ReviewCommandService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/ReviewInternalService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/domain/PointTypeConstants.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/ReviewCommandServiceTest.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/ReviewInternalServiceTest.java
NBT-267 커피챗 도메인 팁 지급 리뷰 포인트 지급 리팩터링 (close #446)
- 리뷰 작성 메서드에서 외부 서비스 호출 로직과 DB 처리 로직 분리
- 테스트 코드 수정
=> [BE] NBT-267 커피챗 도메인 팁 지급 리뷰 포인트 지급 리팩터링

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/application/controller/PointTransactionCommandController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/application/service/PointTransactionCommandService.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/client/PointTransactionClient.java
NBT-266 구매 알림 도메인 api 주소 restful 하게 변경하기 (close #445)
- controller api 주소 변경
- feignclient api 주소 변경
=> [BE] NBT-266 구매 알림 도메인 api 주소 restful 하게 변경하기

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/controller/CommentController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/controller/PostController.java
=> api mapping 수정

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/application/service/CompletePurchaseService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/application/service/PointTransactionCommandService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/application/service/PurchaseCommandService.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/purchase/command/application/service/CompletePurchaseServiceTest.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/purchase/command/application/service/PurchaseCommandServiceTest.java
NBT-268 구매 도메인 리팩터링(close #448)
- 멘토 권한 구매, 커피챗 구매, 칼럼 구매 DB처리와 외부 서비스 호출 분리
- 테스트 코드 수정
=> [BE] NBT-268 구매 도메인 리팩터링

newbit-feature-service/build.gradle, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/s3/config/S3Config.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/s3/service/S3Uploader.java
Nbt 275 s 3 설정 파일
AWS S3 의존성 추가 및 S3Config / S3Uploader 파일 추가
=> Nbt 275 s 3 설정 파일

newbit-user-service/src/main/java/com/newbit/newbituserservice/auth/entity/RefreshToken.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/User.java
refactor: NBT-279 User 도메인 캡슐화 적용 close #468
=> Nbt 279 user 도메인 캡슐화 점검 코드 수정 및 msa 적용 시 수정 필요 목록 작성

newbit-user-service/src/main/java/com/newbit/newbituserservice/user/controller/UserController.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/controller/UserInfoController.java
refactor: NBT-280 User 도메인 restful-api 변경 close #469
=> refactor: NBT-280 User 도메인 restful-api 변경

newbit-user-service/src/main/java/com/newbit/newbituserservice/auth/entity/RefreshToken.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/controller/MentorController.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/User.java
=> fix: NBT-283 User 도메인 누락코드 수정

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/common/exception/ErrorCode.java
=> refactor : 에러 코드 분리

newbit-gateway/src/main/java/com/newbit/newbitgateway/dto/ApiResponse.java, newbit-gateway/src/main/java/com/newbit/newbitgateway/exception/BusinessException.java, newbit-gateway/src/main/java/com/newbit/newbitgateway/exception/ErrorCode.java, newbit-gateway/src/main/java/com/newbit/newbitgateway/exception/GlobalExceptionHandler.java, newbit-gateway/src/main/java/com/newbit/newbitgateway/jwt/GatewayJwtTokenProvider.java
=> refactor : 에러 형식 통일

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/common/exception/ErrorCode.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/entity/Comment.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/entity/Post.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/entity/PostCategory.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/repository/PostCategoryRepository.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostCategoryService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/command/application/service/ReportCommandService.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceNoticeTest.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceTest.java
=> post 캡슐화 점검

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/domain/aggregate/ColumnPurchaseHistory.java
- 구매 도메인 엔티티에 protected 어노테이션 적용하기
- ColumnPurchaseHistory에 @NoArgsConstructor(access = AccessLevel.PROTECTED) 적용
=> [BE] NBT-288 구매 도메인 엔티티에 protected 어노테이션 적용하기

newbit-gateway/src/main/java/com/newbit/newbitgateway/error/JwtErrorCode.java, newbit-gateway/src/main/java/com/newbit/newbitgateway/filter/JwtAuthenticationFilter.java, newbit-gateway/src/main/java/com/newbit/newbitgateway/jwt/GatewayJwtTokenProvider.java
[NBT-281] [BE] Gateway JWT 인증 실패 시 JSON 형식 에러 응답 추가 close #472
[NBT-281]: https://kimjy3520.atlassian.net/browse/NBT-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 281 be gateway jwt 인증 실패 시 json 형식 에러 응답 추가 

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/controller/PostImageController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/request/PostCreateRequest.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/response/PostDetailResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/response/PostResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/entity/Post.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostImageService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/s3/service/S3Uploader.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/column/service/ColumnServiceTest.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceTest.java
=> post 이미지 첨부 기능 추가

newbit-gateway/src/main/java/com/newbit/newbitgateway/jwt/GatewayJwtTokenProvider.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/common/exception/ErrorCode.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/dto/request/UserRequestDTO.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/Job.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/Techstack.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/User.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/UserAndTechstack.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/UserAndTechstackId.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/repository/JobRepository.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/repository/TechstackRepository.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/repository/UserAndTechstackRepository.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/service/UserService.java
회원가입 시 직종, 기술스택 받을 수 있도록 정보 추가
=> Nbt 289 be 회원가입 시 필요한 정보 추가

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/dto/request/CreateSeriesRequestDto.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/SeriesService.java
Nbt 295 빈 시리즈 생성 가능하게 수정	
service, requestDto 파일 수정
=> Nbt 295 빈 시리즈 생성 가능하게 수정

newbit-user-service/src/main/java/com/newbit/newbituserservice/common/exception/ErrorCode.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/controller/UserInfoController.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/dto/request/UserInfoUpdateRequestDTO.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/dto/request/UserProfileInfoUpdateRequestDTO.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/User.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/repository/UserAndTechstackRepository.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/service/UserInfoService.java
[NBT-290] [BE] 유저 프로필, 계정 정보 수정 분리 및 정보 추가
[NBT-290]: https://kimjy3520.atlassian.net/browse/NBT-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nbt 290 be 유저 프로필 계정 정보 수정 분리 및 정보 추가

newbit-gateway/src/main/java/com/newbit/newbitgateway/filter/JwtAuthenticationFilter.java, newbit-gateway/src/main/java/com/newbit/newbitgateway/jwt/GatewayJwtTokenProvider.java
[[NBT-299] [BE] gateway 에러코드 수정 close #506 
[NBT-299]: https://kimjy3520.atlassian.net/browse/NBT-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NBT-299] [BE] gateway 에러코드 수정

newbit-user-service/src/main/java/com/newbit/newbituserservice/common/exception/ErrorCode.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/service/UserService.java
=> Nbt 300 be 회원가입 기능 오류 수정

newbit-user-service/src/main/java/com/newbit/newbituserservice/common/exception/ErrorCode.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/controller/UserInfoController.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/dto/request/MentorCoffeechatInfoDTO.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/dto/request/MentorIntroduceInfoDTO.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/Mentor.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/repository/MentorRepository.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/service/UserInfoService.java
=> Nbt 291 be 멘토 정보 수정 기능 구현

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/controller/PostImageController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/request/PostCreateRequest.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/response/PostDetailResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/response/PostResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/entity/Post.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostImageService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceTest.java
=> Nbt 287 게시판 이미지 첨부 기능 추가

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/response/PostDetailResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/entity/Attachment.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java
=> Nbt 315 post attachment 엔티티 추가

newbit-frontend/package-lock.json, newbit-frontend/package.json, newbit-frontend/postcss.config.js, newbit-frontend/src/features/coffeeletter/components/Chat.vue, newbit-frontend/src/features/coffeeletter/components/ChatRoomList.vue, newbit-frontend/src/features/coffeeletter/router.js, newbit-frontend/src/features/coffeeletter/views/CoffeeLetterChatView.vue, newbit-frontend/src/features/perk/components/ColorCard.vue, newbit-frontend/src/features/perk/components/ColorQuiz.vue, newbit-frontend/src/features/perk/router.js, newbit-frontend/src/features/perk/views/FreePersonalQuizView.vue, newbit-frontend/src/features/perk/views/PerkListView.vue, newbit-frontend/src/features/perk/views/PersonalQuizView.vue, newbit-frontend/src/features/report/components/AdminSideBar.vue, newbit-frontend/src/features/report/components/RelatedReportList.vue, newbit-frontend/src/features/report/components/ReportItem.vue, newbit-frontend/src/features/report/components/ReportList.vue, newbit-frontend/src/features/report/router.js, newbit-frontend/src/features/report/views/ReportDashboardView.vue, newbit-frontend/src/features/report/views/ReportDetailView.vue, newbit-frontend/src/features/report/views/ReportListView.vue, newbit-frontend/src/style.css, newbit-frontend/tailwind.config.js
Close #526
- router.js 
- 빈 components
- 빈 views
=> Nbt 307 fe 심리테스트 views components routing

newbit-frontend/package-lock.json, newbit-frontend/package.json, newbit-frontend/postcss.config.js, newbit-frontend/src/features/report/components/AdminSideBar.vue, newbit-frontend/src/features/report/components/RelatedReportList.vue, newbit-frontend/src/features/report/components/ReportItem.vue, newbit-frontend/src/features/report/components/ReportList.vue, newbit-frontend/src/features/report/router.js, newbit-frontend/src/features/report/views/ReportDashboardView.vue, newbit-frontend/src/features/report/views/ReportDetailView.vue, newbit-frontend/src/features/report/views/ReportListView.vue, newbit-frontend/src/style.css, newbit-frontend/tailwind.config.js
Close #525 
- router.js 
- 빈 components
- 빈 views
=> feat:NBT-306 관리자 신고 페이지 views, routing 추가

newbit-frontend/package-lock.json, newbit-frontend/package.json, newbit-frontend/postcss.config.js, newbit-frontend/src/features/coffeeletter/components/Chat.vue, newbit-frontend/src/features/coffeeletter/components/ChatRoomList.vue, newbit-frontend/src/features/coffeeletter/router.js, newbit-frontend/src/features/coffeeletter/views/CoffeeLetterChatView.vue, newbit-frontend/src/features/perk/components/ColorCard.vue, newbit-frontend/src/features/perk/components/ColorQuiz.vue, newbit-frontend/src/features/perk/router.js, newbit-frontend/src/features/perk/views/FreePersonalQuizView.vue, newbit-frontend/src/features/perk/views/PerkListView.vue, newbit-frontend/src/features/perk/views/PersonalQuizView.vue, newbit-frontend/src/features/product/components/ProductForm.vue, newbit-frontend/src/features/product/components/ProductList.vue, newbit-frontend/src/features/product/router.js, newbit-frontend/src/features/product/views/ProductCreateView.vue, newbit-frontend/src/features/product/views/ProductEditView.vue, newbit-frontend/src/features/product/views/ProductListView.vue, newbit-frontend/src/features/product/views/ProductManageView.vue, newbit-frontend/src/features/report/components/AdminSideBar.vue, newbit-frontend/src/features/report/components/RelatedReportList.vue, newbit-frontend/src/features/report/components/ReportItem.vue, newbit-frontend/src/features/report/components/ReportList.vue, newbit-frontend/src/features/report/router.js, newbit-frontend/src/features/report/views/ReportDashboardView.vue, newbit-frontend/src/features/report/views/ReportDetailView.vue, newbit-frontend/src/features/report/views/ReportListView.vue, newbit-frontend/src/style.css, newbit-frontend/tailwind.config.js
Close #527 
- router.js 
- 빈 components
- 빈 views
=> Nbt 308 fe 상품 관리 views components routing

newbit-frontend/package-lock.json, newbit-frontend/package.json, newbit-frontend/postcss.config.js, newbit-frontend/src/features/coffeeletter/components/Chat.vue, newbit-frontend/src/features/coffeeletter/components/ChatRoomList.vue, newbit-frontend/src/features/coffeeletter/router.js, newbit-frontend/src/features/coffeeletter/views/CoffeeLetterChatView.vue, newbit-frontend/src/features/report/components/AdminSideBar.vue, newbit-frontend/src/features/report/components/RelatedReportList.vue, newbit-frontend/src/features/report/components/ReportItem.vue, newbit-frontend/src/features/report/components/ReportList.vue, newbit-frontend/src/features/report/router.js, newbit-frontend/src/features/report/views/ReportDashboardView.vue, newbit-frontend/src/features/report/views/ReportDetailView.vue, newbit-frontend/src/features/report/views/ReportListView.vue, newbit-frontend/src/style.css, newbit-frontend/tailwind.config.js
Close #528 
- router.js 
- 빈 components
- 빈 views
=> Nbt 309 fe 커피레터 component 작성

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/ColumnController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/SeriesController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/repository/ColumnRepository.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/repository/SeriesRepository.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ColumnService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/SeriesService.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/column/service/ColumnServiceTest.java, newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/column/service/SeriesServiceTest.java
Nbt 313 칼럼 시리즈 페이징 처리	
칼럼 및 시리즈 페이징 처리 및 테스트 코드 수정
=> Nbt 313 칼럼 시리즈 페이징 처리

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostInternalService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java
close #549 
게시글 조회 시 카테고리 정보 누락으로 인한 NullPointerException 발생 수정
- []  
- []
=> PostService 코드 수정

newbit-frontend/src/components/common/Header.vue
없음	
- Header의 admin nav-link v-if 조건 해제(관리자 페이지 연결 테스트)
- 나중에 authStore, 로그인 기능 구현되면 코드 원복 필요(주석 처리 해놓음)
=> chore: Header의 admin nav-link v-if 조건 해제

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/dto/request/CoffeechatCreateRequest.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatCommandService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/common/exception/ErrorCode.java
=> Nbt 310 커피챗 목록 조회 상세 조회 시 사용되는 dto 분리

newbit-frontend/src/features/coffeechat/components/MentorProfileCard.vue, newbit-frontend/src/features/coffeechat/components/RegisterCoffeechatForm.vue, newbit-frontend/src/features/coffeechat/components/UserProfileCard.vue, newbit-frontend/src/features/coffeechat/router.js, newbit-frontend/src/features/coffeechat/views/CoffeechatMainView.vue, newbit-frontend/src/features/coffeechat/views/CoffeechatRegisterView.vue, newbit-frontend/src/features/mypage/router.js, newbit-frontend/src/features/mypage/views/CoffeechatDetailView.vue, newbit-frontend/src/features/mypage/views/CoffeechatListView.vue, newbit-frontend/src/features/mypage/views/MyReviewsView.vue, newbit-frontend/src/features/mypage/views/ReviewRegisterView.vue, newbit-frontend/src/features/profile/router.js, newbit-frontend/src/features/profile/views/MentorProfileDetailView.vue, newbit-frontend/src/features/profile/views/UserProfileDetailView.vue, newbit-frontend/src/router/index.js
=> Nbt 365 fe 커피챗 기능을 프론트로 구현하기 위한 뼈대 구성

newbit-frontend/package-lock.json, newbit-frontend/package.json, newbit-frontend/src/features/mypage/components/HistoryItem.vue, newbit-frontend/src/features/mypage/components/HistoryList.vue, newbit-frontend/src/features/mypage/views/DiamondHistoryView.vue
- 회원 다이아 내역 페이지 구현
- 회원 다이아 내역 페이지 구현
=> [FE]NBT-369 회원 다이아 내역 페이지 구현

newbit-frontend/src/features/mypage/components/HistoryItem.vue, newbit-frontend/src/features/mypage/components/HistoryList.vue, newbit-frontend/src/features/mypage/router.js, newbit-frontend/src/features/mypage/views/DiamondHistoryView.vue, newbit-frontend/src/features/mypage/views/PointHistoryView.vue, newbit-frontend/src/features/mypage/views/SaleHistoryView.vue
=> [FE] NBT-370 판매 내역 페이지 구현

newbit-frontend/package-lock.json, newbit-frontend/package.json, newbit-frontend/src/assets/styles/styleguide.css, newbit-frontend/src/features/column/components/ColumnCard.vue, newbit-frontend/src/features/column/components/ColumnRequestForm.vue, newbit-frontend/src/features/column/router.js, newbit-frontend/src/features/column/views/ColumnDetailView.vue, newbit-frontend/src/features/column/views/ColumnEditRequestView.vue, newbit-frontend/src/features/column/views/ColumnRequestView.vue, newbit-frontend/src/main.js
Nbt 343 fe 칼럼 요청 페이지 구현 등록 수정	
칼럼 등록/수정 요청 공통 컴포넌트 폼 구현
등록 뷰, 수정 뷰 구현
=> Nbt 343 fe 칼럼 요청 페이지 구현 등록 수정

newbit-frontend/src/components/layout/DefaultLayout.vue
없음
DeafultLayout.vue height 속성 제거
=> feat:NBT-363 DefaultLayout.vue height 속성 제거

newbit-frontend/src/features/column/views/ColumnDetailView.vue
[FE] 칼럼 상세 조회 페이지 구현(멘토용)	
NBT-373 칼럼 상세 조회 멘토용 버튼 구현
=> [FE] NBT 37칼럼 상세 조회 페이지 구현(멘토용)

newbit-frontend/src/features/user/components/LoginForm.vue, newbit-frontend/src/features/user/router.js, newbit-frontend/src/features/user/views/LoginView.vue
=> Nbt 325 fe 로그인 view components router 구현

newbit-frontend/package-lock.json, newbit-frontend/src/features/user/components/FindIdForm.vue, newbit-frontend/src/features/user/router.js, newbit-frontend/src/features/user/views/FindIdView.vue, newbit-frontend/src/features/user/views/LoginView.vue
=> Nbt 326 fe 아이디찾기 view components router 구현

newbit-frontend/src/features/user/components/FindIdForm.vue, newbit-frontend/src/features/user/components/LoginForm.vue, newbit-frontend/src/features/user/components/SignUpForm.vue
=> refactor: NBT-376 스타일가이드 및 tailwind 적용

newbit-frontend/src/features/user/components/FindPasswordForm.vue, newbit-frontend/src/features/user/router.js, newbit-frontend/src/features/user/views/FindPasswordView.vue
=> Nbt 327 fe 비밀번호찾기 view components router 구현

newbit-frontend/src/features/admin/views/ColumnApprovalView.vue, newbit-frontend/src/features/column/components/ColumnCard.vue, newbit-frontend/src/features/column/views/ColumnListView.vue
Nbt 345 fe 칼럼 요청 관리자용 페이지 구현	
칼럼 등록, 수정, 삭제 요청 목록 관리자용 페이지 구현
=> Nbt 345 fe 칼럼 요청 관리자용 페이지 구현

newbit-frontend/src/features/admin/router.js, newbit-frontend/src/features/admin/views/ColumnApprovalDetailView.vue
NBT-346 칼럼 요청 상세 조회 관리자용 페이지 구현
칼럼 요청 상세 내역 조회 관리자용 페이지 구현 및 라우터 생성
=> NBT-346 칼럼 요청 상세 조회 관리자용 페이지 구현

newbit-frontend/src/features/mypage/router.js, newbit-frontend/src/features/mypage/views/ColumnRequestHistoryView.vue
Nbt 344 fe 칼럼 요청 내역 페이지 구현	
칼럼 요청 내역 페이지 구현
=> Nbt 344 fe 칼럼 요청 내역 페이지 구현

newbit-frontend/src/components/common/PagingBar.vue, newbit-frontend/src/features/mypage/components/HistoryList.vue, newbit-frontend/src/features/mypage/views/DiamondHistoryView.vue, newbit-frontend/src/features/mypage/views/PointHistoryView.vue
- pagingbar 공통 컴포넌트 생성
- pagingbar 공통 컴포넌트 생성
=> Nbt 388 fe pagingbar 공통 컴포넌트 생성

newbit-frontend/src/features/column/components/ColumnCard.vue, newbit-frontend/src/features/mypage/components/MyPageSideBar.vue, newbit-frontend/src/features/mypage/router.js, newbit-frontend/src/features/mypage/views/PurchasedColumnsView.vue
- 구매한 칼럼 페이지 구현	
- 구매한 칼럼 페이지 구현
=> Nbt 352 fe 구매한 칼럼 페이지 구현

newbit-frontend/src/features/mypage/router.js, newbit-frontend/src/features/mypage/views/AccountDeleteView.vue
=> Nbt 387 fe 회원탈퇴 페이지 구현

newbit-frontend/src/features/mypage/views/AccountEditView.vue
- 회원 정보 수정 페이지 구현
- 회원 정보 수정 페이지 구현
=> feat: NBT-386 회원 정보 수정 페이지 구현

newbit-frontend/src/features/mypage/components/MyProfileEditForm.vue, newbit-frontend/src/features/mypage/views/MyProfileEditView.vue
- 프로필 수정 페이지 구현
- 프로필 수정 페이지 구현
=> Nbt 384 fe 프로필 수정 페이지 구현

newbit-frontend/src/features/column/components/ColumnRequestForm.vue
NBT-380 칼럼 이미지 첨부 url base64 인코딩	
칼럼 등록 기능 base64 처리 적용 완료 (API 연동 전)
=> NBT-380 칼럼 이미지 첨부 url base64 인코딩

newbit-frontend/src/features/mypage/components/MentorProfileEditForm.vue, newbit-frontend/src/features/mypage/components/MyProfileEditForm.vue, newbit-frontend/src/features/mypage/views/AccountEditView.vue, newbit-frontend/src/features/mypage/views/MentorProfileEditView.vue
- 멘토 프로필 수정 페이지 구현
- 멘토 프로필 수정 페이지 구현
=> Nbt 385 fe 멘토 프로필 수정 페이지 구현

newbit-frontend/src/api/axios.js, newbit-frontend/src/api/user.js, newbit-frontend/src/features/user/components/SignUpForm.vue, newbit-frontend/src/features/user/views/SignUpView.vue, newbit-frontend/src/main.js, newbit-gateway/src/main/resources/application.yml
Nbt 378 fe sigup api 연동
회원가입, 로그인 등 회원 관련 api가 먼저 작업되어야 한다고 생각해서 먼저 작업해봤습니다. (api 연동이 오래 걸릴 것 같아서요...) 피드백 부탁드립니다.
(현재 DB에 존재하는 직업, 기술스택 리스트를 보여주는 api가 없어서  null 값을 넣고 가입해야합니다.)
- [x ] 회원가입 가입 시 DB에 저장되는 거 확인
=> Nbt 378 fe sigup api 연동

newbit-frontend/src/components/common/Header.vue, newbit-frontend/src/features/coffeechat/api.js, newbit-frontend/src/features/coffeechat/components/RegisterCoffeechatForm.vue, newbit-frontend/src/features/coffeechat/router.js, newbit-frontend/src/features/coffeechat/views/CoffeechatRegisterView.vue
=> Nbt 334 fe 커피챗 신청 페이지 생성

newbit-frontend/src/features/mypage/components/MyPageSideBar.vue, newbit-frontend/src/features/mypage/router.js, newbit-frontend/src/features/mypage/views/MyColumnsView.vue, newbit-frontend/src/features/mypage/views/MyPostsView.vue, newbit-frontend/src/features/mypage/views/MySeriesView.vue, newbit-frontend/src/features/mypage/views/SubscribedSeriesView.vue
- 마이페이지 side bar 목록 수정 및 라우터 수정
- 마이페이지 side bar 목록 수정
- 라우터 수정
- 회원 탈퇴 추가
=> Nbt 395 fe 마이페이지 side bar 목록 수정 및 라우터 수정

newbit-user-service/src/main/java/com/newbit/newbituserservice/user/controller/JobTechStackController.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/dto/response/JobDTO.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/dto/response/TechstackDTO.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/repository/JobRepository.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/repository/TechstackRepository.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/service/JobTechstackService.java
Nbt 393 be 기술스택 직업 조회 api 생성
- [ x]  포스트맨
=> Nbt 393 be 기술스택 직업 조회 api 생성

newbit-frontend/package-lock.json, newbit-frontend/package.json, newbit-frontend/src/features/column/components/SeriesCreateModal.vue, newbit-frontend/src/features/column/components/SeriesEditModal.vue, newbit-frontend/src/features/column/views/SeriesListView.vue
Nbt 348 fe 시리즈 발행 수정 모달 구현	
시리즈 발행 모달, 수정 모달 구현
시리즈 썸네일 비율 16:9로 맞춤
=> Nbt 348 fe 시리즈 발행 수정 모달 구현

newbit-frontend/src/features/payment/components/PaymentWidget.vue, newbit-frontend/src/features/payment/views/SuccessView.vue
이미 닫힘	
- UX 관련 일부 기능 추가.(결제 승인 timeout 적용 등)
=> feat:NBT-392 UX 관련 기능 일부 추가(결제 승인 timeout적용), 버그 발견(지라에 등록함)

newbit-frontend/src/features/post/components/CategorySidebar.vue, newbit-frontend/src/features/post/views/PostListView.vue
close #680 
게시판 카테고리 사이드바 UI, 목록 수정
페이징 바 공통 컴포넌트로 변경
=> [FE] 게시판 카테고리 목록 수정

newbit-frontend/src/features/profile/components/UserProfileSideBar.vue, newbit-frontend/src/features/profile/components/UserProfileTabBar.vue, newbit-frontend/src/features/profile/views/UserProfileDetailView.vue
=> Nbt 328 fe 다른 유저 프로필 조회 view components router 구현

newbit-frontend/src/features/profile/components/MentorProfileSideBar.vue, newbit-frontend/src/features/profile/components/MentorProfileTabBar.vue, newbit-frontend/src/features/profile/views/MentorProfileDetailView.vue
=> Nbt 329 fe 멘토 프로필 조회 view components router 구현

newbit-frontend/src/features/post/components/CategorySidebar.vue, newbit-frontend/src/features/post/components/DeleteConfirmModal.vue, newbit-frontend/src/features/post/components/PostSearchBar.vue, newbit-frontend/src/features/post/components/ReportModal.vue, newbit-frontend/src/features/post/components/SortTabs.vue, newbit-frontend/src/features/post/views/PostCreateView.vue, newbit-frontend/src/features/post/views/PostDetailView.vue, newbit-frontend/src/features/post/views/PostEditView.vue, newbit-frontend/src/features/post/views/PostListView.vue
=> [FE]  게시판 search bar 수정

newbit-frontend/src/features/mypage/router.js, newbit-frontend/src/features/mypage/views/CoffeechatCancelView.vue, newbit-frontend/src/features/mypage/views/CoffeechatDetailView.vue
=> feat: 커피챗 취소 시 나타나는 모달 생성

newbit-frontend/src/components/common/Header.vue, newbit-frontend/src/features/notification/components/NotificationDropdown.vue, newbit-frontend/src/features/notification/components/NotificationItem.vue
=> Nbt 305 fe 알림 드롭다운 생성

newbit-frontend/src/features/mypage/views/CoffeechatCancelView.vue
=> feat : 커피챗 취소 페이지 생성

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/query/controller/ReportQueryController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/query/dto/ReportedCommentResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/query/dto/ReportedPostResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/query/dto/response/ReportDTO.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/query/service/ReportQueryService.java, newbit-feature-service/src/main/resources/mappers/report/ReportMapper.xml, newbit-frontend/src/api/payment.js, newbit-frontend/src/api/report.js, newbit-frontend/src/features/report/components/CommentReportList.vue, newbit-frontend/src/features/report/components/PostReportList.vue, newbit-frontend/src/features/report/layout/AdminSideBar.vue, newbit-frontend/src/features/report/router.js, newbit-frontend/src/features/report/views/CommentReportDetailView.vue, newbit-frontend/src/features/report/views/PostReportDetailView.vue, newbit-frontend/src/features/report/views/ReportListView.vue
Close #713
- 신고 기능 백엔드 프론트 연동
- 상세 조회는 게시판 api 연동 완료된 이후 마무리 예정
=> feat: NBT-411 신고 기능 백엔드 프론트 연동, 상세 조회는 게시판 기능 완성된 이후 마무리 예정

newbit-frontend/src/api/user.js, newbit-frontend/src/features/mypage/views/AccountDeleteView.vue
- 회원 탈퇴 api 연결
- 회원 탈퇴 api 연결
- 탈퇴후 메인페이지로 라우팅
=> Nbt 404 fe 회원 탈퇴 api 연결

newbit-frontend/src/api/user.js, newbit-frontend/src/features/user/views/FindPasswordView.vue
=> Nbt 416 fe 비밀번호 찾기 api 연결

newbit-frontend/src/features/mypage/components/CoffeechatDetail.vue, newbit-frontend/src/features/mypage/views/CoffeechatDetailMentorView.vue
=> Nbt 337 fe 커피챗 승인 모달 컴포넌트 생성

newbit-frontend/src/features/mypage/components/MyProfileEditForm.vue, newbit-frontend/src/features/mypage/views/MyProfileEditView.vue
- 유저 프로필 수정 api 연결
- 유저 프로필 수정 api 연결
=> Nbt 420 fe 유저 프로필 수정 api 연결

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/payment/query/controller/PaymentQueryController.java, newbit-frontend/src/features/mypage/components/HistoryItem.vue, newbit-frontend/src/features/mypage/components/HistoryList.vue, newbit-frontend/src/features/mypage/router.js, newbit-frontend/src/features/mypage/views/PurchaseHistory.vue, newbit-frontend/src/features/product/views/ProductPaymentView.vue
Close #714 
- 결제 내역 프론트 구현
- 결제 userId 하드코딩 제거 => pinia 스토어 사용
=> feat: NBT-412 결제 내역 조회 구현, 결제 pinia Store 적용.(기존 하드코딩 삭제)

newbit-frontend/src/api/purchase.js, newbit-frontend/src/features/mypage/views/PurchasedColumnsView.vue
- 구매한 칼럼 조회 api 연결
- 구매한 칼럼 조회 api 연결
=> Nbt 405 fe 구매한 칼럼 조회 api 연결

newbit-frontend/src/features/post/views/PostCreateView.vue, newbit-frontend/src/features/post/views/PostDetailView.vue, newbit-frontend/src/features/post/views/PostEditView.vue
close #739 	
alert를 toastification으로 변경하였습니다.
=> [FE] alert -> toastification으로 변경

newbit-frontend/src/features/mypage/components/CoffeechatDetail.vue, newbit-frontend/src/features/mypage/router.js, newbit-frontend/src/features/mypage/views/CoffeechatDetailMenteeView.vue
=> Nbt 356 fe 커피챗 상세 커피챗 완료 페이지 생성

newbit-frontend/src/features/mypage/components/CoffeechatDetail.vue, newbit-frontend/src/features/mypage/views/CoffeechatDetailMenteeView.vue
=> Nbt 357 fe 커피챗 상세 커피챗 취소 페이지 생성

newbit-frontend/src/features/coffeechat/views/CoffeechatRegisterView.vue, newbit-frontend/src/features/mypage/components/RegisterReviewForm.vue, newbit-frontend/src/features/mypage/views/CoffeechatDetailMenteeView.vue, newbit-frontend/src/features/mypage/views/ReviewRegisterView.vue
🎯 *작업 개요*
* 별점, 리뷰 내용, 팁 등록 폼 생성
* api 점검
🔧 *작업 상세 내용* 
-
-
✅ *완료 조건*
-
-
=> [NBT-360] [FE] 멘티 리뷰 작성 페이지 생성

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/dto/response/GetMyColumnListResponseDto.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/mapper/ColumnMapper.java
- 작성한 칼럼 조회 api 수정
- 작성일시 추가
- 좋아요 수 삭제
=> Nbt 425 be 작성한 칼럼 조회 api 수정

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/controller/PostController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/repository/PostRepository.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java
UserId로 작성한 글을 목록 조회하는 API 없어서 추가했습니다!
- [x ] Postman
=> Nbt 421 be 유저 프로필 조회용 api 추가

newbit-frontend/src/features/mypage/views/CoffeechatListMentorView.vue, newbit-frontend/src/features/profile/components/ColumnTab.vue, newbit-frontend/src/features/profile/components/MentorProfileTabBar.vue, newbit-frontend/src/features/profile/components/PostTab.vue, newbit-frontend/src/features/profile/components/ReviewTab.vue, newbit-frontend/src/features/profile/components/SeriesTab.vue, newbit-frontend/src/features/profile/views/MentorProfileDetailView.vue
close #606 
- 기본 틀은 다음과 같이 잡아놨습니다
=> Nbt 361 fe 멘토 리뷰 조회 페이지 생성

newbit-frontend/src/api/post.js, newbit-frontend/src/api/user.js, newbit-frontend/src/components/common/PagingBar.vue, newbit-frontend/src/features/profile/components/UserPostListItem.vue, newbit-frontend/src/features/profile/components/UserProfileSideBar.vue, newbit-frontend/src/features/profile/views/UserProfileDetailView.vue, newbit-frontend/src/features/stores/auth.js
=> Nbt 423 fe 유저 프로필 api 연결

newbit-frontend/src/features/stores/auth.js, newbit-gateway/src/main/java/com/newbit/newbitgateway/filter/JwtAuthenticationFilter.java, newbit-gateway/src/main/java/com/newbit/newbitgateway/jwt/GatewayJwtTokenProvider.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/auth/dto/response/TokenResponseDTO.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/auth/repository/RefreshTokenRepository.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/auth/service/AuthService.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/security/JwtTokenProvider.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/security/filter/HeaderAuthenticationFilter.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/security/model/CustomUser.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/entity/User.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/repository/MentorRepository.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/repository/UserRepository.java
=> Nbt 441 fe auth store 필요 필드 추가

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/common/exception/GlobalExceptionHandler.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/notification/command/application/controller/NotificationCommandController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/notification/command/domain/repository/NotificationRepository.java, newbit-frontend/package-lock.json, newbit-frontend/package.json, newbit-frontend/src/App.vue, newbit-frontend/src/api/notification.js, newbit-frontend/src/features/notification/components/NotificationDropdown.vue, newbit-frontend/src/features/stores/notification.js, newbit-gateway/src/main/resources/application.yml
- 알림 관련 api 연동
- SSE연결 수정
- gateway patch요청에 대한 처리 추가
- 읽음처리에 대한 백엔드 코드 수정
- 알림 드롭다운에 api 연동
=> Nbt 399 fe 알림 관련 api 연동

newbit-gateway/src/main/java/com/newbit/newbitgateway/filter/JwtAuthenticationFilter.java
=> fix: NBT-447 코드 수정

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/query/controller/CoffeechatQueryController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/query/controller/ReviewQueryController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/query/dto/request/CoffeechatSearchServiceRequest.java, newbit-feature-service/src/main/resources/mappers/coffeechat/CoffeechatMapper.xml
close #758 
조회 결과
```
{
"success": true,
"data": {
"coffeechats": [
{
"coffeechatId": 13,
"progressStatus": "IN_PROGRESS",
"requestMessage": "안녕하세요 신입입니다.",
"profileImageUrl": null,
"nickname": "mentor"
}
],
"pagination": {
"currentPage": 1,
"totalPage": 1,
"totalItems": 1
}
},
"errorCode": null,
"message": null,
"timestamp": "2025-05-07T01:55:25.5314433"
}
```
=> Nbt 430 be 멘토 멘티 커피챗 목록 조회 api 분리

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/domain/Column.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ColumnRequestService.java, newbit-frontend/src/features/column/components/ColumnCard.vue, newbit-frontend/src/features/column/views/ColumnRequestView.vue
Nbt 444 fe 칼럼 등록 요청 api 연동	
- 칼럼 등록 요청 성공
- 그러나 칼럼 요청 내역 계속 에러남
- 시리즈 부분에 mentorNickname 때문에 sql 에러가 남
- 추후 수정 예정
=> Nbt 444 fe 칼럼 등록 요청 api 연동

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/controller/PostController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/response/PostListResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java, newbit-frontend/src/api/post.js, newbit-frontend/src/features/post/views/PostListView.vue
=> 게시글 목록 api 연결

newbit-frontend/src/api/coffeechat.js, newbit-frontend/src/api/mentor.js, newbit-frontend/src/features/coffeechat/components/RegisterCoffeechatForm.vue, newbit-frontend/src/features/coffeechat/views/CoffeechatRegisterView.vue
=> Nbt 428 fe 커피챗 신청 api 연동

newbit-frontend/src/api/coffeechat.js, newbit-frontend/src/features/mypage/views/CoffeechatListMenteeView.vue, newbit-frontend/src/features/mypage/views/CoffeechatListMentorView.vue
=> Nbt 429 fe 멘토 멘티 커피챗 목록 조회 api 연동

newbit-frontend/src/api/user.js, newbit-frontend/src/components/common/ProfileDropdown.vue, newbit-frontend/src/features/stores/auth.js, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/controller/UserInfoController.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/dto/response/BalanceDTO.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/user/service/UserInfoService.java
- 포인트 다이아 잔여랑 조회 api 추가
- 포인트 다이아 잔여랑 조회 api 추가
- 드롭다운에 현재 잔여량 반영
- authStore에서 잔여량 관리
=> Nbt 454 be 포인트 다이아 잔여랑 조회 api 추가, 드롭다운에 현재 잔여량 반영

newbit-frontend/src/api/post.js, newbit-frontend/src/features/post/views/PostDetailView.vue, newbit-frontend/src/features/post/views/PostEditView.vue
close #805 
게시글 수정 api 연결
게시글 상세조회 api 연결
=> 게시글 수정 api 연결

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/ColumnController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/SeriesController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ColumnService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/SeriesService.java, newbit-frontend/src/api/coffeechat.js, newbit-frontend/src/api/column.js, newbit-frontend/src/features/profile/components/ColumnTab.vue, newbit-frontend/src/features/profile/components/PostTab.vue, newbit-frontend/src/features/profile/components/ReviewTab.vue, newbit-frontend/src/features/profile/components/SeriesTab.vue, newbit-frontend/src/features/profile/components/UserPostListItem.vue, newbit-frontend/src/features/profile/views/MentorProfileDetailView.vue, newbit-frontend/src/features/profile/views/UserProfileDetailView.vue
=> Nbt 448 fe 멘토 프로필 조회 api 연동

newbit-frontend/src/api/post.js, newbit-frontend/src/features/post/views/PostDetailView.vue
=> 게시글 삭제 api 연결

newbit-frontend/src/features/profile/components/ColumnTab.vue, newbit-frontend/src/features/profile/components/PostTab.vue, newbit-frontend/src/features/profile/components/ReviewTab.vue, newbit-frontend/src/features/profile/components/SeriesTab.vue, newbit-frontend/src/features/user/components/FindIdForm.vue, newbit-frontend/src/features/user/components/FindPasswordForm.vue, newbit-frontend/src/features/user/components/LoginForm.vue, newbit-frontend/src/features/user/views/FindIdView.vue, newbit-frontend/src/features/user/views/FindPasswordView.vue, newbit-frontend/src/features/user/views/LoginView.vue
=> Nbt 461 fe 버튼 이벤트 헨들링 수정

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatCommandService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatInternalService.java, newbit-frontend/src/api/coffeechat.js, newbit-frontend/src/features/mypage/views/CoffeechatCancelView.vue, newbit-frontend/src/features/mypage/views/CoffeechatDetailMenteeView.vue
=> Nbt 433 fe 멘티 커피챗 취소 api 연동

newbit-frontend/src/api/column.js, newbit-frontend/src/features/column/components/SeriesCard.vue, newbit-frontend/src/features/mypage/views/LikedContentsView.vue, newbit-frontend/src/features/mypage/views/SubscribedSeriesView.vue
- 구독한 시리즈, 좋아요한 컨텐츠 페이지 구현, api 연결
- 구독한 시리즈, 좋아요한 컨텐츠 페이지 구현
- api 연결
=> Nbt 381 fe 구독한 시리즈, 좋아요한 컨텐츠 페이지 구현, api 연결

newbit-frontend/src/api/post.js, newbit-frontend/src/features/post/views/PostDetailView.vue, newbit-gateway/src/main/resources/application.yaml
=> 댓글 등록, 삭제 api 연결

newbit-frontend/src/api/user.js, newbit-gateway/src/main/java/com/newbit/newbitgateway/filter/JwtAuthenticationFilter.java, newbit-user-service/src/main/java/com/newbit/newbituserservice/security/filter/HeaderAuthenticationFilter.java
=> fix: NBT-466 jwt토큰 버그 수정

newbit-frontend/src/api/purchase.js, newbit-frontend/src/features/perk/components/ColorCard.vue, newbit-frontend/src/features/perk/components/ColorQuiz.vue, newbit-frontend/src/features/perk/views/FreePersonalQuizView.vue, newbit-frontend/src/features/perk/views/PerkListView.vue, newbit-frontend/src/features/perk/views/PersonalQuizView.vue, newbit-frontend/src/router/index.js, newbit-gateway/src/main/resources/application.yaml
Close #572
- 무료 심리테스트 추가
- 유료 심리테스트 구매 로직 적용
=> feat:NBT-407 chatStore 등록, 웹소켓 전역 관리, global.css 수정,

newbit-frontend/src/features/main/components/MainColumnBanner.vue, newbit-frontend/src/features/main/components/MainColumnList.vue, newbit-frontend/src/features/main/components/MainIntroBanner.vue, newbit-frontend/src/features/main/components/MainLoginPromBanner.vue, newbit-frontend/src/features/main/components/MainMentorList.vue, newbit-frontend/src/features/main/components/MainSeriesList.vue, newbit-frontend/src/features/main/components/MainTemplateList.vue, newbit-frontend/src/features/main/views/MainView.vue
=> Nbt 465 fe 메인페이지 구현 및 api 연결

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/AdminColumnController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/dto/response/AdminColumnRequestResponseDto.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/mapper/ColumnMapper.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/AdminColumnService.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ColumnRequestService.java, newbit-frontend/src/api/column.js, newbit-frontend/src/features/admin/views/ColumnApprovalDetailView.vue, newbit-frontend/src/features/admin/views/ColumnApprovalView.vue
Nbt 460 fe 칼럼 요청 승인 거절 상세 페이지 api 연동	
- 칼럼 승인/거절 상세 페이지 API 연동
- AdminColumnReqeustResponseDto에 content 필드 추가
- 관리자용 칼럼 요청 상세 조회 API 추가
=> Nbt 460 fe 칼럼 요청 승인 거절 상세 페이지 api 연동

newbit-frontend/src/api/coffeeletter.js, newbit-frontend/src/features/mypage/components/CoffeechatDetail.vue, newbit-frontend/src/features/mypage/views/CoffeechatDetailMenteeView.vue
=> Nbt 436 fe 커피레터 입장 시 커피레터 id 조회 api 연동

newbit-frontend/src/api/coffeechat.js, newbit-frontend/src/features/mypage/components/CoffeechatDetail.vue
=> Nbt 435 fe 커피챗 종료 확정 api 연동

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/query/dto/response/CoffeechatDto.java, newbit-frontend/src/api/coffeechat.js, newbit-frontend/src/features/mypage/views/CoffeechatDetailMenteeView.vue
=> Nbt 437 fe 구매확정 api 연동

newbit-frontend/package-lock.json, newbit-frontend/package.json, newbit-frontend/src/api/post.js, newbit-frontend/src/features/post/components/ReportModal.vue, newbit-frontend/src/features/post/views/PostDetailView.vue
=> 게시글, 댓글 신고 api 연결

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/query/dto/response/CoffeechatDto.java, newbit-feature-service/src/main/resources/mappers/coffeechat/CoffeechatMapper.xml
=> feat: 관련 dto 수정

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/application/service/CompletePurchaseService.java, newbit-frontend/src/api/purchase.js, newbit-frontend/src/features/column/views/ColumnDetailView.vue
=> Nbt 467 fe 칼럼 구매 구현

newbit-frontend/src/features/column/views/ColumnDetailView.vue
feat: NBT-442 auth.js에서 mentorId로 받아오기
=> feat: NBT-442 auth.js에서 mentorId로 받아오기

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ColumnService.java
- 칼럼 상세조회시 예외처리 수정
- 본인 칼럼의 경우 예외 발생 안되도록 수정
- 무료 칼럼의 경우 예외 발생 안되도록 수정
=> feat: NBT-469 칼럼 상세조회시 예외처리 수정

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/controller/ReviewCommandController.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/application/service/CompletePurchaseService.java, newbit-frontend/src/api/coffeechat.js, newbit-frontend/src/features/mypage/components/RegisterReviewForm.vue, newbit-frontend/src/features/mypage/views/CoffeechatDetailMenteeView.vue, newbit-frontend/src/features/mypage/views/ReviewRegisterView.vue
=> Nbt 438 fe 리뷰 작성 api 연동

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatCommandService.java
=> feat: 알림 무시:

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ColumnService.java, newbit-frontend/src/features/admin/views/ColumnApprovalDetailView.vue, newbit-frontend/src/features/column/components/SeriesCard.vue, newbit-frontend/src/features/column/views/ColumnDetailView.vue, newbit-frontend/src/features/column/views/ColumnEditRequestView.vue, newbit-frontend/src/features/column/views/SeriesListView.vue, newbit-frontend/src/features/mypage/views/ColumnRequestHistoryView.vue, newbit-frontend/src/features/stores/auth.js
=> Nbt 471 fe 칼럼 상세 조회 멘토용 사용자용

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/dto/response/GetSeriesListResponseDto.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/SeriesService.java, newbit-frontend/src/features/column/components/SeriesCard.vue, newbit-frontend/src/features/column/views/SeriesListView.vue
=> feat: NBT-472 시리즈 목록 조회

newbit-frontend/src/App.vue, newbit-frontend/src/components/common/Header.vue, newbit-frontend/src/features/coffeeletter/router.js, newbit-frontend/src/features/payment/components/PaymentWidget.vue, newbit-frontend/src/features/payment/router.js, newbit-frontend/src/features/perk/router.js, newbit-frontend/src/features/product/router.js, newbit-frontend/src/router/index.js
=> chore: 어드민 페이지, 상품 페이지 등 라우터 가드 적용, 로그아웃시 로그인페이지로 리다이렉트 명시

newbit-frontend/src/components/common/AuthRequiredModal.vue
=> fix:authRequirdModal.vue 업로드

newbit-frontend/src/features/main/components/MainLoginPromBanner.vue
=> refactor: NBT-474 로그인 시 로그인 버튼 사라지도록 수정

newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/response/PostDetailResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/dto/response/PostListResponse.java, newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java, newbit-frontend/src/features/post/views/PostDetailView.vue
close #859 
댓글, 게시글 삭제 버튼이 해당 게시글 작성자에게만 보이게 조건 변경
=> 댓글, 게시글 삭제 버튼이 해당 게시글 작성자에게만 보이게 조건 변경

newbit-frontend/src/api/post.js, newbit-frontend/src/features/post/views/PostListView.vue
=> 게시글 검색 api 연결
