letsgetit-hanwha-be15/be15-2nd-letsgetit-newbit

- src/main/java/com/newbit/post/controller/CommentController.java
- src/main/java/com/newbit/post/controller/PostController.java
- src/main/java/com/newbit/post/dto/request/CommentCreateRequest.java
- src/main/java/com/newbit/post/dto/response/CommentResponse.java
- src/main/java/com/newbit/post/entity/Comment.java
- src/main/java/com/newbit/post/repository/CommentRepository.java
- src/main/java/com/newbit/post/service/CommentService.java
- src/main/java/com/newbit/post/service/PostService.java
- src/test/java/com/newbit/post/service/CommentServiceTest.java
- src/test/java/com/newbit/post/service/PostServiceTest.java
close #91 
게시글에 댓글을 등록할 수 있는 기능 구현
댓글 등록 요청을 처리하는 CommentService.createComment() 메서드 추가
댓글 등록 요청을 위한 DTO CommentCreateRequest 생성
댓글 등록 결과를 반환하는 DTO CommentResponse 생성
댓글 엔티티(Comment) 생성 및 Post와 연관관계 설정
댓글 등록 단위 테스트 코드 작성 (CommentServiceTest)
댓글 등록 시 게시글 존재 여부 확인 및 예외 처리
> feat: NBT-103 댓글 등록 기능 구현

- src/main/java/com/newbit/common/exception/ErrorCode.java
- src/main/java/com/newbit/purchase/command/application/service/PurchaseCommandService.java
- src/main/java/com/newbit/purchase/command/domain/aggregate/DiamondHistory.java
- src/main/java/com/newbit/user/entity/User.java
- src/main/java/com/newbit/user/service/UserService.java
- src/test/java/com/newbit/purchase/command/application/service/PurchaseCommandServiceTest.java
feat: NBT-147 커피챗 다이아 환불 기능 구현 (close #164)
- 커피챗 다이아 환불요청시 다이아 내역 테이블에 내역 생성
- 환불 요청한 회원의 보유 다이아 값 변경(증가)
- 커피챗 구매, 커피챗 환불시 판매내역 내역 생성 메서드 호출 삭제 후 메서드 분리
> feat: NBT-147 커피챗 다이아 환불 기능 구현

- src/main/java/com/newbit/post/controller/PostController.java
- src/main/java/com/newbit/post/dto/response/PostDetailResponse.java
- src/main/java/com/newbit/post/entity/Post.java
- src/main/java/com/newbit/post/entity/PostCategory.java
- src/main/java/com/newbit/post/repository/PostRepository.java
- src/main/java/com/newbit/post/service/PostService.java
- src/test/java/com/newbit/post/service/PostServiceTest.java
close #89 
- 게시글 상세 정보를 조회하는 기능 추가
- 제목, 내용, 작성일, 수정일 등 기본 정보 포함
- 삭제된 게시글은 조회되지 않도록 예외 처리
- 연관된 정보 함께 반환:
- 작성자 이름 (User.userName)
- 카테고리 이름 (PostCategory.name)
- 해당 게시글에 달린 댓글 리스트 (Comment)
> feat: NBT-101 be 게시글 상세 조회 기능 구현

- src/main/java/com/newbit/column/controller/ColumnController.java
- src/main/java/com/newbit/column/domain/Column.java
- src/main/java/com/newbit/column/dto/response/GetColumnDetailResponseDto.java
- src/main/java/com/newbit/column/dto/response/GetColumnListResponseDto.java
- src/main/java/com/newbit/column/mapper/ColumnMapper.java
- src/main/java/com/newbit/column/repository/ColumnRepository.java
- src/main/java/com/newbit/column/service/ColumnRequestService.java
- src/main/java/com/newbit/column/service/ColumnService.java
- src/main/java/com/newbit/common/exception/ErrorCode.java
- src/test/java/com/newbit/column/service/ColumnServiceTest.java
Nbt 156 공개 칼럼 리스트 조회 기능 구현	
1. 공개된 칼럼(isPublic = true)만 조회하는 기능 구현
2. 생성일(createdAt) 기준 내림차순으로 정렬되도록 설정
3. 관련 Repository 메서드 정의:
4. findAllByIsPublicTrueOrderByCreatedAtDesc()
5. 목록 조회 페이징 처리 완료
> Nbt 156 공개 칼럼 리스트 조회 기능 구현

- src/main/java/com/newbit/report/command/application/service/ReportCommandService.java
- src/main/java/com/newbit/report/command/domain/repository/ReportRepository.java
- src/main/java/com/newbit/report/command/infrastructure/repository/JpaReportRepository.java
- src/test/java/com/newbit/report/command/application/service/ReportCommandServiceTest.java
Close #158
- 댓글 자동 삭제(Soft delete) 기능을 구현한다.
- 신고 등록시 댓글의 신고 카운트가 +1 증가하고, 신고 카운트가 50(임계치)를 넘길 시 자동으로 삭제
> feat:NBT-145-be-신고-50-회-누적-댓글-자동-soft-delete-기능-시스템'

- src/main/java/com/newbit/post/controller/PostController.java
- src/main/java/com/newbit/post/repository/PostRepository.java
- src/main/java/com/newbit/post/service/PostService.java
- src/test/java/com/newbit/post/service/PostServiceNoticeTest.java
- src/test/java/com/newbit/post/service/PostServiceTest.java
close #94 
- 공지사항 등록 기능 추가 (POST /posts/notices)
- 관리자(ADMIN 권한)만 등록 가능하도록 권한 검사 로직 적용
- 일반 게시글과 구분하기 위해 isNotice = true로 저장
> Nbt 106 be 공지사항 등록 기능 구현

- src/main/java/com/newbit/post/controller/PostController.java
- src/main/java/com/newbit/post/service/PostService.java
- src/test/java/com/newbit/post/service/PostServiceNoticeTest.java
close #93 	
관리자 전용 공지사항 삭제 기능 구현
로그인한 사용자 권한이 ROLE_ADMIN일 경우에만 삭제 가능
권한 없을 경우 SecurityException 발생
> Nbt 105 be 공지사항 삭제 기능 구현

- src/main/java/com/newbit/common/config/SwaggerConfig.java
- src/main/java/com/newbit/post/controller/PostController.java
- src/main/java/com/newbit/post/service/PostService.java
- src/test/java/com/newbit/post/service/PostServiceTest.java
- 게시글 수정 시 인증된 사용자만 접근 가능하도록 변경
- 기존에는 인증 없이도 게시글 수정 요청이 가능했으나, @PreAuthorize("isAuthenticated()") 어노테이션을 컨트롤러에 추가하여 인증 필수로 설정함
- 게시글 작성자만 수정 가능하도록 서비스 로직 강화
- 게시글의 userId와 현재 로그인한 사용자의 userId를 비교하여 일치하지 않을 경우 SecurityException 발생
> fix: 게시글 수정 시 인증된 사용자만 가능하도록 기능 추가

- src/main/java/com/newbit/column/controller/SeriesController.java
- src/main/java/com/newbit/column/domain/Column.java
- src/main/java/com/newbit/column/domain/Series.java
- src/main/java/com/newbit/column/dto/request/CreateSeriesRequestDto.java
- src/main/java/com/newbit/column/dto/response/CreateSeriesResponseDto.java
- src/main/java/com/newbit/column/mapper/SeriesMapper.java
- src/main/java/com/newbit/column/repository/SeriesRepository.java
- src/main/java/com/newbit/column/service/SeriesService.java
- src/main/java/com/newbit/common/exception/ErrorCode.java
- src/test/java/com/newbit/column/service/SeriesServiceTest.java
Nbt 87 be 시리즈 생성 기능 구현	
- 기존 칼럼들을 묶어 하나의 시리즈로 등록할 수 있는 시리즈 생성 기능 추가
- 제약 조건
- 최소 1개 이상의 칼럼을 포함해야 함
- 해당 칼럼들은 본인의 칼럼이어야 함
- 이미 시리즈에 포함된 칼럼은 추가할 수 없음
- 시리즈 생성 시, 각 칼럼에 시리즈 연관관계 설정 (column.updateSeries(series) 호출)
> Nbt 87 be 시리즈 생성 기능 구현

- src/main/java/com/newbit/coffeechat/command/application/controller/CoffeechatCommandController.java
- src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
- src/main/java/com/newbit/coffeechat/command/domain/aggregate/Coffeechat.java
- src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
close #64 
Nbt 76 be 멘티구매확정 기능 구현
구매도매인의 판매확정 서비스와 연결
> Nbt 76 be 멘티구매확정 기능 구현

- src/main/java/com/newbit/notification/command/application/controller/NotificationCommandController.java
- src/main/java/com/newbit/notification/command/application/dto/request/NotificationSendRequest.java
- src/main/java/com/newbit/notification/command/application/dto/response/NotificationSendResponse.java
- src/main/java/com/newbit/notification/command/application/service/NotificationCommandService.java
- src/main/java/com/newbit/notification/command/domain/repository/NotificationRepository.java
- src/main/java/com/newbit/notification/command/infrastructure/SseEmitterRepository.java
- src/main/java/com/newbit/notification/query/controller/NotificationQueryController.java
- src/main/java/com/newbit/notification/query/dto/NotificationResponse.java
- src/main/java/com/newbit/notification/query/mapper/NotificationQueryMapper.java
- src/main/java/com/newbit/notification/query/repository/NotificationRepository.java
- src/main/java/com/newbit/notification/query/service/NotificationQueryService.java
- src/main/resources/mappers/notification/NotificationMapper.xml
- src/test/java/com/newbit/notification/command/application/service/NotificationCommandServiceTest.java
- src/test/java/com/newbit/notification/query/service/NotificationQueryServiceTest.java
NBT-150 알림 목록 조회 기능 구현(close #167)
- 특정 사용자의 알림 목록을 최신순(createdAt DESC)으로 조회하는 기능 구현
- notification, notification_type 테이블을 조인하여 알림 유형 이름까지 함께 조회
- NotificationQueryService + NotificationQueryMapper + MyBatis XML 매핑 방식으로 구현
- NotificationResponse DTO 정의
- 알림 ID, 내용, 읽음 여부, 생성일시, 알림 유형명 포함
- GET /api/v1/notification 엔드포인트 구현
> [BE] NBT-150 알림 목록 조회 기능 구현

- src/main/java/com/newbit/common/exception/ErrorCode.java
- src/main/java/com/newbit/notification/command/application/controller/NotificationCommandController.java
- src/main/java/com/newbit/notification/command/application/service/NotificationCommandService.java
- src/main/java/com/newbit/notification/command/domain/aggregate/Notification.java
- src/main/java/com/newbit/notification/command/domain/aggregate/NotificationType.java
- src/main/java/com/newbit/notification/command/domain/repository/NotificationRepository.java
- src/test/java/com/newbit/notification/command/application/service/NotificationCommandServiceTest.java
NBT-151 알림 읽음 처리 기능 구현 (close #168)
- notificationId로 특정 알림에 대한 알림 읽음 처리 구현
- 본인의 알림인지 검증하는 로직 추가
- 안읽은 모든 알림에 대해서 읽음처리 구현
> [BE] NBT-151 알림 읽음 처리 기능 구현

- src/main/java/com/newbit/column/controller/SeriesController.java
- src/main/java/com/newbit/column/service/SeriesService.java
- src/test/java/com/newbit/column/service/SeriesServiceTest.java
1. 시리즈 삭제 기능 구현 (DELETE /api/v1/series/{seriesId})
2. 시리즈에 포함된 칼럼들의 series 참조 해제 처리
3. 본인 소유의 시리즈만 삭제 가능하도록 검증 추가
4. SeriesServiceTest에 시리즈 삭제 성공 테스트 추가
5. 존재하지 않는 시리즈인 경우 → SERIES_NOT_FOUND
6. 본인이 소유하지 않은 칼럼이 포함된 시리즈인 경우 → COLUMN_NOT_OWNED
> feat/Nbt 187 시리즈 삭제 기능 구현

- src/main/java/com/newbit/post/controller/CommentController.java
- src/main/java/com/newbit/post/dto/request/CommentCreateRequest.java
- src/main/java/com/newbit/post/service/CommentService.java
- src/test/java/com/newbit/post/service/CommentServiceTest.java
CommentController에 @PreAuthorize("isAuthenticated()") 적용
@AuthenticationPrincipal CustomUser를 통해 로그인한 사용자 정보 전달
CommentService#createComment() 메서드 시그니처 수정: userId → CustomUser 사용
댓글 작성 시 작성자 정보(userId)를 CustomUser에서 추출
테스트 코드 댓글_등록_성공() 수정하여 인증 사용자 기반으로 동작 확인
> Feat 댓글 작성 시 인증된 사용자만 가능하도록 기능 구현

- src/main/java/com/newbit/post/controller/CommentController.java
- src/main/java/com/newbit/post/service/CommentService.java
- src/test/java/com/newbit/post/service/CommentServiceTest.java
close #298 	
- CommentService에 Swagger 태그(@Tag) 추가
- 인증된 사용자만 댓글을 삭제할 수 있도록 보안 로직 추가
- 댓글 작성자 본인만 삭제 가능하도록 조건 추가 (userId 일치 여부 검증)
- CommentService.deleteComment() 메서드에 사용자 인증 및 권한 체크 로직 적용
- CommentController.deleteComment()에 @PreAuthorize("isAuthenticated()") 및 @AuthenticationPrincipal CustomUser user 파라미터 추가
> Nbt 203 be 댓글 삭제 기능 수정 회원 인증

- src/main/java/com/newbit/column/controller/AdminColumnController.java
- src/main/java/com/newbit/column/domain/Column.java
- src/main/java/com/newbit/column/domain/ColumnRequest.java
- src/main/java/com/newbit/column/dto/request/ApproveColumnRequestDto.java
- src/main/java/com/newbit/column/dto/request/RejectColumnRequestDto.java
- src/main/java/com/newbit/column/dto/response/AdminColumnResponseDto.java
- src/main/java/com/newbit/column/mapper/AdminColumnMapper.java
- src/main/java/com/newbit/column/service/AdminColumnService.java
- src/main/java/com/newbit/common/exception/ErrorCode.java
- src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
Nbt 81 be 관리자 칼럼 등록 요청 승인 거절 기능 구현
- /requests/approve/create, /requests/reject/create POST 엔드포인트 추가
- Swagger 설명 어노테이션 적용
- AdminColumnService 로직 구현
- approveCreateColumnRequest(): 승인 처리 및 칼럼 공개 처리
- rejectCreateColumnRequest(): 거절 처리 및 사유 저장
- ColumnRequest → AdminColumnResponseDto 매핑 메서드 추가
- ErrorCode에 INVALID_REQUEST_TYPE 항목 HttpStatus 누락 부분 보완
- 테스트 코드 (AdminColumnServiceTest) 작성
- 승인 성공, 승인 실패(잘못된 타입)
> Nbt 81 be 관리자 칼럼 등록 요청 승인 거절 기능 구현

- src/main/java/com/newbit/common/exception/ErrorCode.java
- src/main/java/com/newbit/post/service/CommentService.java
- src/main/java/com/newbit/post/service/PostService.java
- src/test/java/com/newbit/post/service/CommentServiceTest.java
- src/test/java/com/newbit/post/service/PostServiceNoticeTest.java
- src/test/java/com/newbit/post/service/PostServiceTest.java
close #291 	
ErrorCode enum 수정(게시글 및 댓글 관련 에러 코드 추가 및 정리)
PostService, CommentService 비즈니스 로직 예외 처리 리팩토링
CommentServiceTest, PostServiceTest, PostServiceNoticeTest 단위 테스트 리팩토링
> Nbt 199 게시글 에러 코드 common 패키지의 공통 에러 양식으로 리팩토링

- src/main/java/com/newbit/column/controller/AdminColumnController.java
- src/main/java/com/newbit/column/domain/Column.java
- src/main/java/com/newbit/column/service/AdminColumnService.java
- src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
Nbt 82 be 관리자 칼럼 수정 요청 승인 거절 기능 구현	
- 관리자용 칼럼 수정 요청 승인/거절 기능 구현
- 승인 시: 요청된 내용으로 실제 칼럼 정보 수정
- 거절 시: 거절 사유 및 관리자 ID 저장
> Nbt 82 be 관리자 칼럼 수정 요청 승인 거절 기능 구현

- src/main/java/com/newbit/column/controller/AdminColumnController.java
- src/main/java/com/newbit/column/service/AdminColumnService.java
- src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
Nbt 83 be 관리자 칼럼 삭제 요청 승인 거절 기능 구현	
- 관리자용 칼럼 삭제 요청 승인/거절 기능 구현
- 승인 시: Column.markAsDeleted() 호출하여 deletedAt 필드에 삭제 시간 설정
- 거절 시: 거절 사유(rejectedReason) 및 관리자 ID 저장
- AdminColumnService에 승인/거절 메서드 추가
- approveDeleteColumnRequest()
- rejectDeleteColumnRequest()
> Nbt 83 be 관리자 칼럼 삭제 요청 승인 거절 기능 구현

- src/main/java/com/newbit/column/service/AdminColumnService.java
- src/main/java/com/newbit/like/service/LikeCommandService.java
- src/main/java/com/newbit/notification/command/application/controller/NotificationCommandController.java
- src/main/java/com/newbit/notification/command/application/dto/request/NotificationSendRequest.java
- src/main/java/com/newbit/post/service/CommentService.java
- src/main/java/com/newbit/post/service/PostService.java
- src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
- src/test/java/com/newbit/post/service/CommentServiceTest.java
NBT-196 칼럼, 게시글 관련 알림 발송 처리(#286)
- 게시글에 댓글이 생성될 때 게시글의 작성자에게 알림이 발송되도록 한다.
- 사용자가 작성한 게시글, 칼럼에 좋아요가 피보나치 수가 될 때마다 작성자에게 실시간으로 알림이 발송되도록 한다.
- 칼럼에 대한 요청(등록, 수정, 삭제) 결과에 대한 알림 발송 처리
- 코드 수정에 따른 테스트 코드 수정
> [BE] NBT-196 칼럼, 게시글 관련 알림 발송 처리

- src/main/java/com/newbit/purchase/command/domain/aggregate/SaleHistory.java
- src/main/java/com/newbit/purchase/command/domain/repository/SaleHistoryRepository.java
- src/main/java/com/newbit/settlement/controller/MentorSettlementController.java
- src/main/java/com/newbit/settlement/entity/MonthlySettlementHistory.java
- src/main/java/com/newbit/settlement/repository/MonthlySettlementHistoryRepository.java
- src/main/java/com/newbit/settlement/service/MentorSettlementService.java
- src/test/java/com/newbit/settlement/service/MentorSettlementServiceTest.java
Nbt 185 정산 내역 계산 및 생성 기능 구현	
- 월별 미정산 SaleHistory를 기준으로 멘토별 정산 내역 계산
- 멘토별 총 판매 금액을 집계하여 MonthlySettlementHistory 생성 및 저장
- 해당 SaleHistory 항목들을 정산 완료 상태로 변경 (markAsSettled())
- 입력된 year, month 기준으로 정산 대상 기간 산출
- saleHistoryRepository.findAllByIsSettledFalseAndCreatedAtBetween() 호출로 미정산 내역 조회
- 멘토 ID 기준으로 그룹핑 → 멘토별 총합 계산
- MonthlySettlementHistory.of 로 정산 엔티티 생성 후 저장
- 정산 처리된 SaleHistory는 markAsSettled() 호출로 상태 업데이트
> Nbt 185 정산 내역 계산 및 생성 기능 구현

- src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
- src/main/java/com/newbit/coffeeletter/service/MessageServiceImpl.java
- src/main/java/com/newbit/notification/command/application/dto/response/NotificationSendResponse.java
- src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
- src/test/java/com/newbit/coffeeletter/service/MessageServiceTest.java
NBT-211 커피챗 관련 알림 발송 처리(#330)
- 멘티가 커피챗 신청했을 시 멘토에게 알림이 실시간으로 발송되도록 한다.
- 멘토가 요청 거부 시 멘티에게 취소 알림이 실시간으로 발송되도록 한다.
- 멘토와 커피챗 일정 확정 시 멘티에게 알림이 실시간으로 발송되도록 한다.
- 멘티가 커피챗 취소시 멘토에게 알림이 실시간으로 발송되도록 한다.
- 새로운 커피레터 발송시에 실시간으로 알림이 발송되도록 한다.
- 코드 변경에 따른 테스트 코드 수정
￼
- 커피레터 발송시 알림 발송에 대한 테스트 필요
> [BE] NBT-211 커피챗 관련 알림 발송 처리

- src/main/java/com/newbit/common/exception/ErrorCode.java
- src/main/java/com/newbit/settlement/controller/MentorSettlementController.java
- src/main/java/com/newbit/settlement/service/MentorSettlementService.java
- src/test/java/com/newbit/settlement/service/MentorSettlementServiceTest.java
Nbt 186 정산서 이메일 자동 발송 기능 구현	
- SettlementEmailService 클래스 추가
- JavaMailSender를 이용해 정산서 메일 템플릿 발송
- 정산 대상인 mentor에게 해당 월의 정산서 내용을 포함한 이메일 전송
- 정산서 메일 HTML 형식으로 구성
- 월별 정산 내역(MonthlySettlementHistory)을 기반으로 이메일 본문 생성
- 메일 제목: "[Newbit] {{정산 년/월}} 정산서 안내 메일입니다."
> Nbt 186 정산서 이메일 자동 발송 기능 구현

- src/main/java/com/newbit/payment/command/application/service/PaymentCommandService.java
- src/main/java/com/newbit/payment/command/application/service/RefundCommandService.java
- src/main/java/com/newbit/purchase/command/application/service/PurchaseCommandService.java
- src/test/java/com/newbit/payment/command/application/service/PaymentCommandServiceTest.java
- src/test/java/com/newbit/payment/command/application/service/RefundCommandServiceTest.java
- src/test/java/com/newbit/purchase/command/application/service/PurchaseCommandServiceTest.java
NBT-217 다이아몬드 거래 발생시 알림 발송 기능 구현 (#346)
- 다이아몬드 충전, 전체 환불, 부분 환불시 사용자에게 알림 발송
- 다이아몬드로 커피챗, 멘토권한, 칼럼 구매시 구매자에게 알림 발송
- 코드 수정에 따른 테스트 코드 수정
> [BE] NBT-217 다이아몬드 거래 발생시 알림 발송 기능 구현

- src/main/java/com/newbit/payment/command/application/service/PaymentCommandService.java
- src/main/java/com/newbit/payment/command/application/service/RefundCommandService.java
- src/main/java/com/newbit/purchase/command/application/service/DiamondCoffeechatTransactionCommandService.java
- src/main/java/com/newbit/purchase/command/application/service/DiamondTransactionCommandService.java
- src/main/java/com/newbit/purchase/command/domain/aggregate/DiamondTransactionType.java
- src/test/java/com/newbit/payment/command/application/service/PaymentCommandServiceTest.java
- src/test/java/com/newbit/payment/command/application/service/RefundCommandServiceTest.java
- src/test/java/com/newbit/purchase/command/application/service/DiamondTransactionCommandServiceTest.java
NBT-219 다이아 결제 후 회원 다이아 변경 다이아 내역 생성 구현(#349)
- 다이아 결제/환불 후 회원의 보유 다이아가 증감 되도록 구현 (구매 도메인)
- 다이아 결제/환불 후 다이아 내역이 생성되도록 구현 (구매 도메인)
- 결제 후 구매 도메인에 구현된 메서드를 호출하도록 구현 (결제 도메인)
- 전체 환불 후 구매 도메인에 구현된 메서드를 호출하도록 구현 (결제 도메인)
- 부분 환불 후 구매 도메인에 구현된 메서드를 호출하도록 구현 (결제 도메인)
- 코드 수정에 대한 테스트 코드 수정
> [BE] NBT-219 다이아 결제 후 회원 다이아 변경 다이아 내역 생성 구현

- src/main/java/com/newbit/common/exception/ErrorCode.java
- src/main/java/com/newbit/post/service/PostService.java
- src/test/java/com/newbit/post/service/PostServiceTest.java
close #363 
비회원의 게시글 등록 시 NullPointerException 발생 문제 해결
비회원일 경우 BusinessException을 발생시키고, ErrorCode.ONLY_USER_CAN_CREATE_POST를 반환하도록 통일
> fix: 비회원 게시글 등록 시 NullPointerException 발생 문제 해결

- src/main/java/com/newbit/column/service/AdminColumnService.java
- src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
NBT-215 시리즈에 새로운 칼럼 등록시 구독한 사용자들에게 알림 발송 기능구현
- 시리즈에 새로운 칼럼이 등록이 승인되어 발행될 때 시리즈를 구독한 모든 사용자들에게 실시간 알림을 전송
- 칼럼 등록 승인 테스트 코드 수정
> [BE] NBT-215 시리즈에 새로운 칼럼 등록시 구독한 사용자들에게 알림 발송 기능구현

- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/CommentInternalService.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/CommentService.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostInternalService.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java
- newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/CommentServiceTest.java
- newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceNoticeTest.java
- newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceTest.java
NBT-263 게시판 도메인 포인트 지급 리팩터링 (close #442)
- Comment 관련 사이드 이펙트 처리 Service 분리 (포인트 지급, 알림 발송)
- Post 관련 사이드 이펙트 처리 Service 분리 (포인트 지급, 알림 발송)
- Transaction과 FeignClient 호출 로직 분리
- 테스트 코드 수정
> [BE] NBT-263 게시판 도메인 포인트 지급 리팩터링

- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/query/infrastructure/mapper/ReportMapper.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/report/query/infrastructure/repository/MyBatisReportQueryRepository.java
- newbit-feature-service/src/main/resources/mappers/report/ReportMapper.xml
- newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/report/query/infrastructure/repository/MyBatisReportQueryRepositoryTest.java
- newbit-feature-service/src/test/resources/sql/report-test-data.sql
Close #457	
- Report 도메인 조회 관련 기능을 Jpa에서 myBatis 동적 쿼리로 변경
> feat: Report 도메인 jpa 쿼리 서비스들을 myBatis 동적 쿼리 사용하여 코드 간소화

- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatCommandService.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatInternalService.java
- newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
- newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatInternalServiceTest.java
- 커피챗 취소 db처리 로직과 외부 서비스 호출로직 분리(close #464)
- 커피챗 취소 기능에서 Transactional로 처리할 로직 분리
- 테스트 코드 수정 및 작성
> [BE] NBT-277 커피챗 취소 db처리 로직과 외부 서비스 호출로직 분리

- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostInternalService.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java
- newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceTest.java
- 게시글 작성 transactional 분리 (close #544)
- 게시글 등록 로직에서 Transactional이 필요한 DB 처리 로직 분리
- 테스트 코드 수정
> [BE] NBT-316 게시글 작성 transactional 분리

- newbit-frontend/src/features/column/router.js
- newbit-frontend/src/features/column/views/ColumnListView.vue
Nbt 389 fe 라우터 수정 및 칼럼 등록 버튼 클릭 시 경로 설정	
- 문제점
/columns/:id → :id = 'requests' 로 인식됨
"requests"를 :id로 오인해서 ColumnDetailView가 렌더링됨
- 해결책
정적인 경로가 동적 경로보다 먼저 선언되어야 올바르게 동작하기 때문에 라우터에서 경로 순서 변경
> Nbt 389 fe 라우터 수정 및 칼럼 등록 버튼 클릭 시 경로 설정

- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/ColumnImageController.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/SeriesImageController.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/domain/Column.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/dto/response/GetColumnListResponseDto.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/repository/ColumnRepository.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ColumnService.java
- newbit-frontend/src/api/column.js
- newbit-frontend/src/features/column/components/ColumnCard.vue
- newbit-frontend/src/features/column/views/ColumnListView.vue
Nbt 418 fe 칼럼 목록 조회 api 연동	
- 백엔드 createdAt 필드 추가
- mentorNickname 리포지토리 쿼리에서 삭제하고 서비스 로직에서 검색
- 포스트맨 결과 조회 성공 (에러 수정 완료)
- 검색기능, 칼럼 목록 조회 API 연동
> Nbt 418 fe 칼럼 목록 조회 api 연동

- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/dto/response/GetColumnDetailResponseDto.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/repository/ColumnRepository.java
- newbit-frontend/src/features/column/components/ColumnCard.vue
- newbit-frontend/src/features/column/views/ColumnDetailView.vue
Nbt 426 fe 칼럼 상세 조회 api 연동	
- 칼럼 목록에서 클릭했을 때 상세조회 페이지로 넘어가도록 구현
- 작성자 본인만 수정/삭제 버튼 노출하도록 조건 분기하는 작업 추후 authStore에 mentorId 생성시에 구현 예정
- 현재는 칼럼을 구매한 모든 사용자에게 수정/삭제 버튼 보이고 있음
> Nbt 426 fe 칼럼 상세 조회 api 연동

- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/ColumnRequestController.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/SeriesController.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/domain/Series.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/dto/response/GetSeriesListResponseDto.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/repository/ColumnRequestRepository.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/repository/SeriesRepository.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ColumnRequestService.java
- newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/SeriesService.java
- newbit-frontend/src/api/column.js
- newbit-frontend/src/features/mypage/views/ColumnRequestHistoryView.vue
Nbt 449 be 시리즈 목록 조회 dto 생성 및 mentor nickname 필드 수정	
- mentorNickname @Transient 처리
- 시리즈 목록 (공개 조회) DTO 생성
- 시리즈 공개 조회와 내 시리즈 조회 다시 매핑, 포스트맨 에러 해결
- 칼럼 요청 내역 목록 조회 페이지 연동(에러 해결)
- 칼럼 요청 내역 페이징 처리(프론트, 백엔드)
- 칼럼 요청 내역 UI 정렬
> Nbt 449 be 시리즈 목록 조회 dto 생성 및 mentor nickname 필드 수정
